### ISSUE TITLE
Feature Request: Introduce Tags

### ISSUE THREAD

**Issue by Maddosaurus** [RD17/ambar#10]
Hi there!  

I just stumbled upon Ambar and really like the idea as well as the frontend.    
Is there any chance that one could add tags to uploaded documents?  
That would open up so much more options in management and queries.  

(Maybe adding a freetext / transform to tag field right next to the Download button?)   
If you're interested, I would be happy to assist in the realization of features; simply because I see some great potential in Ambar compared to other DMS solutions out there.

Thanks!

Matthias

**Comment by sochix** [comment]
@Maddosaurus hello! This feature is in our internal roadmap. What other DMS solutions did you try?

**Comment by Maddosaurus** [comment]
Mostly open source ones, but it's an ongoing process. I tried
- MayanEDMS
- Paperless
- ecoDMS
- agorum
- seedDMS

and all of them are either feature overkill for my needs, have a rather unappealing GUI or an unstable client that crashes all the time.  
Honestly, I'm just looking for a document archive with OCR, tags, downloadable docs and maybe folders.  
That's why I thought about implementing such a thing for myself - until I discovered your (pretty young) project over here :)

**Comment by jmgilman** [comment]
Any ETA on tag implementation? 

This wonderful tool hits every requirement for me with the exception of tagging. I do receipt management (scanned in as PDF) and need the ability to tag receipts with data like supplier, etc.

**Comment by sochix** [comment]
@jmgilman @Maddosaurus we are working on tags feature. Backend almost done.

**Comment by sochix** [comment]
Tags are available in 0.10.0 release
