### ISSUE TITLE
Ambar Installation: Start Error "cannot create /sys/kernel/mm/transparent_hugepage/enabled"

### ISSUE THREAD

**Issue by rbprimat** [RD17/ambar#103]
I followed the Ambar Installation: Step-by-step guide (https://blog.ambar.cloud/ambar-installation-step-by-step-guide-2/).
Download was successful.
If I start the ambar docker container with: sudo ./ambar.py start I get the following output and error:
`root@dc01:/opt/ambar# ./ambar.py start
 

______           ____     ______  ____       
/\  _  \  /'\_/`\/\  _`\  /\  _  \/\  _`\    
\ \ \L\ \/\      \ \ \L\ \ \ \L\ \ \ \L\ \  
 \ \  __ \ \ \__\ \ \  _ <'\ \  __ \ \ ,  /   
  \ \ \/\ \ \ \_/\ \ \ \L\ \ \ \/\ \ \ \ \  
   \ \_\ \_\ \_\ \_\ \____/ \ \_\ \_\ \_\ \_\
    \/_/\/_/\/_/ \/_/\/___/   \/_/\/_/\/_/\/ /

                                              
Docker version 17.10.0-ce, build f4ffd25
docker-compose version 1.17.0, build ac53b73
vm.max_map_count = 262144
net.ipv4.ip_local_port_range = 15000 61000
net.ipv4.tcp_fin_timeout = 30
net.core.somaxconn = 1024
net.core.netdev_max_backlog = 2000
net.ipv4.tcp_max_syn_backlog = 2048
vm.overcommit_memory = 1
/bin/sh: 1: cannot create /sys/kernel/mm/transparent_hugepage/enabled: Directory nonexistent
Traceback (most recent call last):
  File "./ambar.py", line 264, in <module>
    start(configuration)
  File "./ambar.py", line 207, in start
    setRunTimeOsConstants()    
  File "./ambar.py", line 127, in setRunTimeOsConstants
    runShellCommandStrict('echo never > /sys/kernel/mm/transparent_hugepage/enabled')
  File "./ambar.py", line 64, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' returned non-zero exit status 2
`
Do I need to install mongodb on the host os?

Hardware: Raspberry Pi 3B
OS: Rasbian Linux version 4.9.13-bee42-v8 (root@b90b7cd7fee9) (gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11)

docker info:
`Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.10.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-bee42-v8
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 969.6MiB
Name: dc01
ID: VEV5:3GWF:AS2H:QIIT:47CC:HT6F:SHA7:DGFB:K7JX:FH7V:E3ZB:J4QH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

**Comment by ahs-ckm-server1** [comment]
Might be related to this - try the edit suggested?
https://github.com/RD17/ambar/issues/94

**Comment by sochix** [comment]
@rbprimat Ambar will not run on RaspberryPI sorry.
