### ISSUE TITLE
Tagging API unclear / not working

### ISSUE THREAD

**Issue by adammoore** [RD17/ambar#104]
I was trying to experiment with adding tags to my files via the API but haven't been successful so far

Is it possible to create new tags via the API?

Are there Tag Types other than **auto** and **source**

**Comment by sochix** [comment]
Please, post here you requests.

**Comment by psarin** [comment]
Hi, I would like to reopen this issue - how can we tag files with custom data. For example, I would like to download an HTML page, have Ambar index it, but store the original URL for future use.
