### ISSUE TITLE
Slow Process Rate

### ISSUE THREAD

**Issue by maydo** [RD17/ambar#105]
Hi,

the more files the less processing rate
see screenshot
![ambarrate](https://user-images.githubusercontent.com/27486434/34066929-9c7c02a6-e218-11e7-9afc-814298494b72.jpg)

any ideas ?

**Comment by sochix** [comment]
@maydo what type of storage did you use? Is it SSD or HDD?

**Comment by maydo** [comment]
hi, its running on ssd raid5, there is enough iops

**Comment by sochix** [comment]
@maydo first Ambar process text files, then perform OCR, I think the process rate fall down because of OCR
