### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by mrdan** [RD17/ambar#106]
Installing on ubuntu 16.04, docker-compose version 1.8.0.

Followed the guide (https://blog.ambar.cloud/ambar-installation-step-by-step-guide-2/), but after some downloading I get this error:

> ERROR: Version in "/home/ddoyle/Ambar/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
> Traceback (most recent call last):
>   File "./ambar.py", line 283, in <module>
>     install(configuration)
>   File "./ambar.py", line 202, in install
>     pullImages(configuration)
>   File "./ambar.py", line 134, in pullImages
>     runShellCommandStrict("docker-compose -f {0}/docker-compose.yml pull".format(PATH))
>   File "./ambar.py", line 64, in runShellCommandStrict
>     subprocess.check_call(command, shell = True)
>   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command 'docker-compose -f /home/me/Ambar/docker-compose.yml pull' returned non-zero exit status 1

**Comment by groundwater** [comment]
Same issue on Ubuntu 17.10

```
vagrant@vagrant:~$ uname -a
Linux vagrant 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

vagrant@vagrant:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

vagrant@vagrant:~$ docker -v
Docker version 17.09.1-ce, build 19e2cf6

vagrant@vagrant:~$ docker-compose -v
docker-compose version 1.8.0, build unknown
```

**Comment by sochix** [comment]
@mrdan @groundwater please update your docker to 17.03.0-ce and docker-compose to 1.11.2

**Comment by noviceiii** [comment]
Had the same. 
Had to remove docker-compose.
`sudo apt autoremove --purge  docker-compose`
and then add
`sudo apt install docker-compose.io `(if I remember right)
