### ISSUE TITLE
Initial e-mail does not arrive

### ISSUE THREAD

**Issue by nonylion** [RD17/ambar#107]
Hi.
What conditions must be met to successfully send login credentials?
I'm trying your brilliant software in my internal network and cannot use auth 'none' for security reasons.
Here's my specs:
Ubuntu 16.04.03
Docker: 17.09.1-ce
Docker-compose: 1.18.0

Thanks.

**Comment by sochix** [comment]
@nonylion check that your machine has internet access.

**Comment by nonylion** [comment]
@sochix Of course it has. It's behind nat however. Also no reverse dns. Maybe there's another way to capture that mail?

**Comment by sochix** [comment]
Check if you have access to mandrill.com by ping

**Comment by nonylion** [comment]
@sochix 
mandrill.com does not reply icmp pings, but mandrillapp.com does.
Using tcpdump i've found, ambar doesn't query mandrill.com but mandrillapp.com. Then it 'speaks' with mandrillapp.com for a while, but still no e-mail :(

**Comment by sdrwtf** [comment]
Hello,

i have exact the same problem as the Issue Owner. Therefore i want to provide a little more detailed information which hopefully helps to solve this.

I installed ambar on a VM (Virtualbox) directly behind a router, no firewall in between which can block anything (but also no dedicated IP address).

OS:
```
sdrwtf@ambar-test:/etc/ambar$ lsb_release -irc
Distributor ID: Ubuntu
Release:        16.04
Codename:       xenial
```
Docker:
```
sdrwtf@ambar-test:/etc/ambar$ sudo docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```
Docker Compose:
```
sdrwtf@ambar-test:/etc/ambar$ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9
```
Installation went through without trouble and ambar starts without problems:
```
sdrwtf@ambar-test:/etc/ambar$ sudo ./ambar.py start


______           ____     ______  ____
/\  _  \  /'\_/`\/\  _`\  /\  _  \/\  _`\
\ \ \L\ \/\      \ \ \L\ \ \ \L\ \ \ \L\ \
 \ \  __ \ \ \__\ \ \  _ <'\ \  __ \ \ ,  /
  \ \ \/\ \ \ \_/\ \ \ \L\ \ \ \/\ \ \ \ \
   \ \_\ \_\ \_\ \_\ \____/ \ \_\ \_\ \_\ \_\
    \/_/\/_/\/_/ \/_/\/___/   \/_/\/_/\/_/\/ /



Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a9
vm.max_map_count = 262144
net.ipv4.ip_local_port_range = 15000 61000
net.ipv4.tcp_fin_timeout = 30
net.core.somaxconn = 1024
net.core.netdev_max_backlog = 2000
Creating ambar_db_1       ... done
Creating ambar_redis_1    ... done
Creating ambar_rabbit_1   ... done
Creating ambar_es_1       ... done
Creating ambar_db_1       ...
Creating ambar_webapi_1   ... done
Creating ambar_es_1       ...
Creating ambar_frontend_1 ... done
Creating ambar_frontend_1 ...
Creating ambar_proxy_1    ... done
Ambar is on http://10.90.90.24:80
```
I can sign up with my email address but i don't get the initial email. Ping to mandrillapp.com also works fine:
```
sdrwtf@ambar-test:/etc/ambar$ ping mandrillapp.com
PING mandrillapp.com (52.16.99.88) 56(84) bytes of data.
64 bytes from ec2-52-16-99-88.eu-west-1.compute.amazonaws.com (52.16.99.88): icmp_seq=1 ttl=43 time=44.7 ms
64 bytes from ec2-52-16-99-88.eu-west-1.compute.amazonaws.com (52.16.99.88): icmp_seq=2 ttl=43 time=34.9 ms
64 bytes from ec2-52-16-99-88.eu-west-1.compute.amazonaws.com (52.16.99.88): icmp_seq=3 ttl=43 time=35.7 ms
^C
--- mandrillapp.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 34.959/38.479/44.758/4.453 ms
```

I know i can set `auth` to `none` in `config.json` which then works kind of, but i really would like to have the login functionality.

My actual (unchanged) config.json: [config.json.txt](https://github.com/RD17/ambar/files/1594288/config.json.txt)

and the Docker container logs:

[ambar_crawler_c0.log](https://github.com/RD17/ambar/files/1594279/ambar_crawler_c0.log)
[ambar_db_1.log](https://github.com/RD17/ambar/files/1594280/ambar_db_1.log)
[ambar_es_1.log](https://github.com/RD17/ambar/files/1594281/ambar_es_1.log)
[ambar_frontend_1.log](https://github.com/RD17/ambar/files/1594282/ambar_frontend_1.log)
[ambar_pipeline_p0.log](https://github.com/RD17/ambar/files/1594283/ambar_pipeline_p0.log)
[ambar_proxy_1.log](https://github.com/RD17/ambar/files/1594284/ambar_proxy_1.log)
[ambar_rabbit_1.log](https://github.com/RD17/ambar/files/1594285/ambar_rabbit_1.log)
[ambar_redis_1.log](https://github.com/RD17/ambar/files/1594286/ambar_redis_1.log)
[ambar_webapi_1.log](https://github.com/RD17/ambar/files/1594287/ambar_webapi_1.log)

Hopefully someone can help.

Thanks!

**Comment by sochix** [comment]
Ok, we found the problem - mandrill. We just exceeded the free quota.  Will consider a swicth to another mail service.

**Comment by sdrwtf** [comment]
Thanks for the reply @sochix ! Maybe it's worth a thought to give the user the option to set a own smtp server / mail relay during installation process. This would also give the option to run ambar in a local environment without permanent web access (e.g. company internal networks).

**Comment by cerberus10** [comment]
Hi I am having the same issue. It seems that the quota is still full. 
Waiting on my email to try your software. 
Is this also happening in the Enterprise versions?

**Comment by ekeskin** [comment]
Any progress on this ?
Just got same problem. Local smtp server could be a great option to have.

**Comment by PhilG2G** [comment]
Same problem for me. I didn't receive the password by email. Why the access is not allowed by a classic default login/password system ?

**Comment by runnermhr** [comment]
Same problem for me. I didn't receive the password by email. What I have to do?

**Comment by rosweiler** [comment]
Same here, no email arriving.

**Comment by sochix** [comment]
Sorry guys for such a long wait time... We'll fix it.

**Comment by sgarwood** [comment]
Hi,
Any progress on this?

+1 With @sdrwtf to allow for local SMTP mail server

**Comment by geekspeed** [comment]
Any progress? Or way to manually setup a user?

**Comment by sdrwtf** [comment]
@geekspeed if you just want to have a peek on it without having an actual login (the system is open then) you can edit the config.json and change the `auth` setting to `none`:

`"auth": "basic"` -> `"auth": "none"`

Then you're able to have a look at the frontend without an login.

Anyway we should keep in mind that there are only two guys working on this project and i presume they're doing this in their spare time. So we should be patient, I think.

**Comment by runnermhr** [comment]
Is it possible to create a local login with multiple users?

**Comment by sdrwtf** [comment]
@runnermhr you can find the information at the bottom of [https://ambar.cloud/]( https://ambar.cloud/) - if you use the community edition (which is free) you can only set up one user. If you need more than one user you need to  use the enterprise edition (price on request).

But that's nothing this issue is about. The problem which is discussed here is that the initial emails which should provide the login information is not arriving because the mail service which is currently used is not working anymore. So at the moment it is not possible at all to set up a user till this problem is fixed.

**Comment by josselinlbe** [comment]
+1 for local SMTP mail server!

**Comment by sochix** [comment]
In the latest version of Ambar we removed users functionality. We decided that it can be done much better via nginx proxy and base auth
