### ISSUE TITLE
(Question) File Linking or preserveOriginals?

### ISSUE THREAD

**Issue by noviceiii** [RD17/ambar#109]
Dear all

Thank you for that great contribution!

I use ambar at home now with the aim of a modern, sophisticated paperless home office (well, I never find my papers again to be honest otherwise :-) ..).

I have the samba server and ambar on the same machine. Therefore I have disabled (preserveOriginals=false) to save disk space.

Now, I lack of the possibility to directly click the original files.
Is there a way I can do one of the following things (if not, may I place a feature request?)?

1/ 
Should I enhance the GUI in that way, so it links to the full path of the original source file in its samba folder? If yes, what program code would you suggest to edit/ at what location?

2/
Shall I enable preserveOriginals? 
Would there be a way to delete processed original files?

Kind regards
novice

**Comment by sochix** [comment]
Hi @noviceiii , 

please submit the first option as a feature request

**Comment by noviceiii** [comment]
my pleasure!
It is #109 #112
