### ISSUE TITLE
Feature Request: Manipulate items via API or Frontend

### ISSUE THREAD

**Issue by oddomatik** [RD17/ambar#11]
It would be nice to be able to manipulate or remove items from the index either via API or frontend. It does look like perhaps we can work with elasticsearch API, but through the ambar-provided API would be desirable.

**Comment by sochix** [comment]
> It would be nice to be able to manipulate or remove items from the index either via API or frontend. 

What kind of manipulation do you want?
We can't easily remove files -> because it'll be added again each time you setup a scheduled crawling
We can add only 'RESET INDEX' button -> which will drop the whole user-index in ElasticSearch

**Comment by sochix** [comment]
No answer from issue opener for 29 days
