### ISSUE TITLE
Feature request: link to file of origin

### ISSUE THREAD

**Issue by noviceiii** [RD17/ambar#112]
Raised feature request as suggested in issue #109  by sochix. 

**Description:**
There is a samba server on the same machine as ambar or in an accessible network. It could be handy to link search results directly to the source files. 

**as a User:**
As a User, I can search for a document in ambar. I see an additional "download arraow" next to the existing one. When hoovering it says "Download from Origin". It also looks a little different than the arrow existing. When I click on the new arrow, the file download starts from the directory/source the document was scanned.

**as an Administrator:**
I can see a new value in config.json "OriginLinking" with valid values of true or false (boolean).
If true
.    all indexed documents are linked to the directory of origin
if false
.    no changes as of today

**System**
The path to dir is taken from settings XML locations:host_name | locations:ip_address / locations:location.
However, maybe it is probably better to introduce a new (optional) value in settings -> locations e.g
_locations:OriginLink_

**Comment by hbh7** [comment]
That would be nice to have. I don't even see a download button currently, unless I'm missing something.

**Comment by sochix** [comment]
Done in the latest version

**Comment by noviceiii** [comment]
Thank you! Gonna test.
(haven't figured out how to use it yet..)
