### ISSUE TITLE
Spanish language support  in defaultLangAnalyzer

### ISSUE THREAD

**Issue by cerberus10** [RD17/ambar#116]
Hi I think that adding Spanish is a good ida. Due to it being the second most spoken language.
Can I help in the support?

**Comment by juanfcocontreras** [comment]
@sochix Wasn't it already implemented for the next version #93?

**Comment by cerberus10** [comment]
This is really useful, i will try it. Thank you very much for your link this is really useful to me

**Comment by cerberus10** [comment]
This is really useful, i will try it. Thank you very much for your link this is really useful to me
