### ISSUE TITLE
ambar not working fresh install

### ISSUE THREAD

**Issue by jamesjara** [RD17/ambar#119]
Could guys help us with a fresh installation try?

I have tried digital ocean, AWS EC2 fresh start
Sudo apt-get install docker-ce=17.03.0~ce-0~ubuntu-xenial
I'm no pasting the logs because there are many issues, so could you just try it from a fresh install?

**Comment by sochix** [comment]
@jamesjara not constructive

**Comment by jamesjara** [comment]
What do you need from me? I have been trying 4 days your steps and even debugging the docker without success, just let me know how I could help you

**Comment by sochix** [comment]
@jamesjara please can you desrcibe a bit `many issues`, so we can select the first one

**Comment by jamesjara** [comment]
@sochix discovered! we need to add the minimum requirements as at least 2GB of memory for the ES
