### ISSUE TITLE
Spanish language support in defaultLangAnalyzer

### ISSUE THREAD

**Issue by cerberus10** [RD17/ambar#125]
The spanish language analyzer is supposed to have been added in #93 but it still doesnt work. 
 https://github.com/RD17/ambar/issues/93.

I have changed the config.json to analyzer_es, but ambar still shows analyzer_en in the web gui

**Comment by juanfcocontreras** [comment]
As I mentioned [here](https://github.com/RD17/ambar/issues/116#issuecomment-359404023), it's supposed to be already implemented in the **next version**, but not the current one.

**Comment by cerberus10** [comment]
I though you meant the currenr one.

**Comment by sochix** [comment]
[Check our support options](https://github.com/RD17/ambar#support)

**Comment by juanfcocontreras** [comment]
Sorry for the question, but it's not clear for me.

In https://github.com/RD17/ambar/issues/93#issuecomment-345616122 you said it was going to be implemented in next version. So, is it already implemented in 2.0?

**Comment by sochix** [comment]
@juanfcocontreras nope, we're not added SPA support, but we canadd it as a paid feature

**Comment by juanfcocontreras** [comment]
Sure! Good luck!
