### ISSUE TITLE
Error when starting Ambar: subprocess.CalledProcessError: Command 'sysctl -w vm.max_map_count=262144' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by JakubA3informatics** [RD17/ambar#128]
Hello,

I'm getting this error when I'm trying to start Ambar and I cannot figure out the issue:

`subprocess.CalledProcessError: Command 'sysctl -w vm.max_map_count=262144' returned non-zero exit status 1.`

The system I'm also trying to use Ambar is my Mac and I do not found any instructions for it.

Thanks

**Comment by sochix** [comment]
Try the latest version of Ambar
