### ISSUE TITLE
Something went wrong on VM and AWS ec2 instance Ubuntu 16.04/14.04

### ISSUE THREAD

**Issue by aashish** [RD17/ambar#129]
@hartmch @bdevelops

I have successfully installed as per instructions with Message "Ambar is running on http://x.x.x.x:80". 
The Url shows default Nginx details as
![screenshot from 2018-02-10 23 47 59](https://user-images.githubusercontent.com/133621/36065207-917426e6-0ebd-11e8-8344-d5408dba9d52.png)

Logs:
![screenshot from 2018-02-10 23 47 49](https://user-images.githubusercontent.com/133621/36065208-a0ea5f14-0ebd-11e8-9996-90dab771525a.png)

anything idea? While able to successfully install on local Ubuntu 14.04 LTS

Thank you,
Aashish

**Comment by sochix** [comment]
Try the latest version or request for a [paid support](https://github.com/RD17/ambar#support)
