### ISSUE TITLE
Cluster with 6 nodes - How to Install?

### ISSUE THREAD

**Issue by prof-schacht** [RD17/ambar#133]
Hi,

I have a question. We have a cluster of 6 nodes and would like to install ambar on it.
Is there a documentation how to install the certain components of ambar on different nodes.
And the ES Nodes on all six?

Just another question:
Is there a script how to get ambar running on docker swarm?

Thanks for your hints.
BR

**Comment by sochix** [comment]
There is no documentation for it as for now, because only EE supports multi-node environments.

**Comment by sochix** [comment]
@prof-schacht you need to modify ambar docker-compose.yml
