### ISSUE TITLE
FrontEnd Webpack Compile

### ISSUE THREAD

**Issue by tanh314** [RD17/ambar#134]
I am looking to make static image adjustments to the FrontEnd of Ambar.  I run the following command to bundle using WebPack:

## Command
`npm run deploy:prod`

I receive the following error:
## Error
`app:bin:compile Compiler encountered an error. Error: Webpack compiler encountered errors
    at /home/scott/Downloads/FrontEnd/build/webpack-compiler.js:24:23
    at Compiler.<anonymous> (/home/scott/Downloads/FrontEnd/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/home/scott/Downloads/FrontEnd/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/home/scott/Downloads/FrontEnd/node_modules/webpack/lib/Compiler.js:187:11)
    at /home/scott/Downloads/FrontEnd/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/home/scott/Downloads/FrontEnd/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/home/scott/Downloads/FrontEnd/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/home/scott/Downloads/FrontEnd/node_modules/webpack/lib/Compiler.js:267:14)
    at /home/scott/Downloads/FrontEnd/node_modules/async/lib/async.js:52:16
    at done (/home/scott/Downloads/FrontEnd/node_modules/async/lib/async.js:246:17)
    at /home/scott/Downloads/FrontEnd/node_modules/async/lib/async.js:44:16
    at /home/scott/Downloads/FrontEnd/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15) +5ms
`

## Log File
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'deploy:prod' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose run-script [ 'predeploy:prod', 'deploy:prod', 'postdeploy:prod' ]
5 info lifecycle ambar-frontend@0.0.1~predeploy:prod: ambar-frontend@0.0.1
6 silly lifecycle ambar-frontend@0.0.1~predeploy:prod: no script for predeploy:prod, continuing
7 info lifecycle ambar-frontend@0.0.1~deploy:prod: ambar-frontend@0.0.1
8 verbose lifecycle ambar-frontend@0.0.1~deploy:prod: unsafe-perm in lifecycle true
9 verbose lifecycle ambar-frontend@0.0.1~deploy:prod: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/scott/Downloads/FrontEnd/node_modules/.bin:/home/scott/bin:/home/scott/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle ambar-frontend@0.0.1~deploy:prod: CWD: /home/scott/Downloads/FrontEnd
11 silly lifecycle ambar-frontend@0.0.1~deploy:prod: Args: [ '-c', 'better-npm-run deploy:prod' ]
12 silly lifecycle ambar-frontend@0.0.1~deploy:prod: Returned: code: 1  signal: null
13 info lifecycle ambar-frontend@0.0.1~deploy:prod: Failed to exec deploy:prod script
14 verbose stack Error: ambar-frontend@0.0.1 deploy:prod: `better-npm-run deploy:prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ambar-frontend@0.0.1
16 verbose cwd /home/scott/Downloads/FrontEnd
17 error Linux 4.10.0-28-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "deploy:prod"
19 error node v7.10.1
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error ambar-frontend@0.0.1 deploy:prod: `better-npm-run deploy:prod`
23 error Exit status 1
24 error Failed at the ambar-frontend@0.0.1 deploy:prod script 'better-npm-run deploy:prod'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the ambar-frontend package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     better-npm-run deploy:prod
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs ambar-frontend
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls ambar-frontend
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
`

**Comment by tanh314** [comment]
Found my issue.  It was a syntax error:

`  app:build:webpack-compiler Module build failed: SyntaxError: Unexpected token, expected ; (5:48)
  app:build:webpack-compiler 
  app:build:webpack-compiler   3 | export const DETAILED_VIEW = 'DETAILED_VIEW'
  app:build:webpack-compiler   4 | export const TABLE_VIEW = 'TABLE_VIEW'
  app:build:webpack-compiler > 5 | export const STATISTICS_VIEW = 'STATISTICS_VIEW'export const MYCONTRACTS_VIEW = 'MYCONTRACTS_VIEW'
  app:build:webpack-compiler     |                                                 ^
  app:build:webpack-compiler 
  app:build:webpack-compiler Error
  app:build:webpack-compiler     at transpile (/home/scott/Downloads/FrontEnd/node_modules/babel-loader/lib/index.js:61:13)
  app:build:webpack-compiler     at /home/scott/Downloads/FrontEnd/node_modules/babel-loader/lib/fs-cache.js:79:18
  app:build:webpack-compiler     at ReadFileContext.callback (/home/scott/Downloads/FrontEnd/node_modules/babel-loader/lib/fs-cache.js:15:14)
  app:build:webpack-compiler     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
  app:build:webpack-compiler  @ ./src/utils/index.js 36:17-39 +3ms
`

**Comment by shellyear** [comment]
> Found my issue. It was a syntax error:
> 
> ` app:build:webpack-compiler Module build failed: SyntaxError: Unexpected token, expected ; (5:48) app:build:webpack-compiler app:build:webpack-compiler 3 | export const DETAILED_VIEW = 'DETAILED_VIEW' app:build:webpack-compiler 4 | export const TABLE_VIEW = 'TABLE_VIEW' app:build:webpack-compiler > 5 | export const STATISTICS_VIEW = 'STATISTICS_VIEW'export const MYCONTRACTS_VIEW = 'MYCONTRACTS_VIEW' app:build:webpack-compiler | ^ app:build:webpack-compiler app:build:webpack-compiler Error app:build:webpack-compiler at transpile (/home/scott/Downloads/FrontEnd/node_modules/babel-loader/lib/index.js:61:13) app:build:webpack-compiler at /home/scott/Downloads/FrontEnd/node_modules/babel-loader/lib/fs-cache.js:79:18 app:build:webpack-compiler at ReadFileContext.callback (/home/scott/Downloads/FrontEnd/node_modules/babel-loader/lib/fs-cache.js:15:14) app:build:webpack-compiler at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13) app:build:webpack-compiler @ ./src/utils/index.js 36:17-39 +3ms`

Can u please deeper explain, how did you solved it. I have the same issue. Thanks :)
