### ISSUE TITLE
ambar-startup missing

### ISSUE THREAD

**Issue by kevin939** [RD17/ambar#136]
I  tried to install ambar as described in the installation guide - failed as it couldn't fetch the docker image (it appears to be missing from the repository)

**Comment by sochix** [comment]
Hello, 
it's our fault. 

Please, update ambar.py and try again.

**Comment by kevin939** [comment]
Hi, Thank you for the fast response. Unfortunately I get the same problem:

Trying to pull repository docker.io/ambar/ambar-startup ...
repository docker.io/ambar/ambar-startup not found: does not exist or no pull access
Traceback (most recent call last):
  File "./ambar.py", line 233, in <module>
    install()
  File "./ambar.py", line 191, in install
    pullStartupImage()
  File "./ambar.py", line 126, in pullStartupImage
    runShellCommandStrict("docker pull {0}/{1}".format(DOCKER_REPO, STARTUP_IMAGE))
  File "./ambar.py", line 64, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker pull ambar/ambar-startup:latest' returned non-zero exit status 1.

cheers

Kevin

**Comment by sochix** [comment]
Can you please remove all Ambar files (ambar.py, /opt/ambar, etc/ambar)  and try again? If something fails please paste your ambar.py here

**Comment by kevin939** [comment]
Hi, removed them all

[root@apxdev-xx-1 kh]# rm /opt/ambar
rm: cannot remove ‘/opt/ambar’: No such file or directory
[root@apxdev-xx-1 kh]# rm /etc/ambar
rm: cannot remove ‘/etc/ambar’: No such file or directory
[root@apxdev-xx-1 kh]# rm ambar.py
rm: cannot remove ‘ambar.py’: No such file or directory
[root@apxdev-xx-1 kh]# rm /etc/ambar.yml
rm: cannot remove ‘/etc/ambar.yml’: No such file or directory

downloaded the latest amber.py:

wget -O ambar.py https://static.ambar.cloud/ambar.py
chmod +x ambar.py

[root@apxdev-xx-1 kh]# ./ambar.py install
Docker version 1.13.1, build 774336d/1.13.1
Please specify path to store Ambar data (Default: /opt/ambar). Type "Y" to confirm or type in another path
/root/kh/ambar
Please specify language analyzer (Default: ambar_en). Type "Y" to confirm or type in another language analyzer
y
Assigning  IP address to Ambar, type "Y" to confirm or type in another IP address...
y
Assigning 80 port address to Ambar, type "Y" to confirm or type in another port...
y
Trying to pull repository docker.io/ambar/ambar-startup ...
repository docker.io/ambar/ambar-startup not found: does not exist or no pull access
Traceback (most recent call last):
  File "./ambar.py", line 231, in <module>
    install()
  File "./ambar.py", line 190, in install
    pullStartupImage()
  File "./ambar.py", line 125, in pullStartupImage
    runShellCommandStrict("docker pull {0}/{1}".format(DOCKER_REPO, STARTUP_IMAGE))
  File "./ambar.py", line 64, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker pull ambar/ambar-startup:latest' returned non-zero exit status 1.


hope that helps


cheers


Kevin

**Comment by sochix** [comment]
It was another bug on our side, please download ambar.py and try again

**Comment by kevin939** [comment]
Hi, better but still a problem:

Trying to pull repository docker.io/ambar/ambar-crawler ...
latest: Pulling from docker.io/ambar/ambar-crawler
Digest: sha256:121dd9d1ce739a255d4b9a764acb0a133a206a46a2e12a389a3f3100e23c4512
Status: Image is up to date for docker.io/ambar/ambar-crawler:latest
Trying to pull repository docker.io/ambar/ambar-pipeline ...
latest: Pulling from docker.io/ambar/ambar-pipeline
Digest: sha256:54fd53343f535a1bb7474822a847c85f40b5505907357184796818b202dd9913
Status: Image is up to date for docker.io/ambar/ambar-pipeline:latest
ERROR: The Compose file '/root/kh/docker-compose.yml' is invalid because:
Unsupported config option for services.redis: 'sysctls'
services.webapi.depends_on contains an invalid type, it should be an array
services.proxy.depends_on contains an invalid type, it should be an array
services.frontend.depends_on contains an invalid type, it should be an array
Traceback (most recent call last):
  File "./ambar.py", line 283, in <module>
    install(configuration)
  File "./ambar.py", line 202, in install
    pullImages(configuration)
  File "./ambar.py", line 134, in pullImages
    runShellCommandStrict("docker-compose -f {0}/docker-compose.yml pull".format(PATH))
  File "./ambar.py", line 64, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker-compose -f /root/kh/docker-compose.yml pull' returned non-zero exit status 1.

cheers

Kevin

**Comment by sochix** [comment]
Seems like you have a wrong version of docker or docker-compose

We recommend to use:

```
Docker version 17.06.2-ce, build cec0b72
docker-compose version 1.16.1, build 6d1ac21
```

**Comment by kevin939** [comment]
We are running on Centos 7.x (x=4). The docker comes from RedHat and identifies itself as the 1.3 and they claim it’s the “latest”......will try the docker repositories

cheers

Keivn

**Comment by kevin939** [comment]
I uninstalled/installed following the instructions here: https://docs.docker.com/install/linux/docker-ce/centos/#install-docker-ce-1

docker --version
Docker version 17.12.1-ce, build 7390fc6



I regret there is no difference:

latest: Pulling from ambar/ambar-crawler
Digest: sha256:121dd9d1ce739a255d4b9a764acb0a133a206a46a2e12a389a3f3100e23c4512
Status: Downloaded newer image for ambar/ambar-crawler:latest
latest: Pulling from ambar/ambar-pipeline
Digest: sha256:54fd53343f535a1bb7474822a847c85f40b5505907357184796818b202dd9913
Status: Downloaded newer image for ambar/ambar-pipeline:latest
ERROR: The Compose file '/root/kh/docker-compose.yml' is invalid because:
Unsupported config option for services.redis: 'sysctls'
services.webapi.depends_on contains an invalid type, it should be an array
services.proxy.depends_on contains an invalid type, it should be an array
services.frontend.depends_on contains an invalid type, it should be an array
Traceback (most recent call last):
  File "./ambar.py", line 283, in <module>
    install(configuration)
  File "./ambar.py", line 202, in install
    pullImages(configuration)
  File "./ambar.py", line 134, in pullImages
    runShellCommandStrict("docker-compose -f {0}/docker-compose.yml pull".format(PATH))
  File "./ambar.py", line 64, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker-compose -f /root/kh/docker-compose.yml pull' returned non-zero exit status 1.

**Comment by kevin939** [comment]
Hi, I started again -  completely uninstalled docker and cleaned everything removing all previous images. Downloaded and installed docker from the docker website (docker–ce latest) and tried again. Same problem
Status: Downloaded newer image for ambar/ambar-pipeline:latest
ERROR: The Compose file '/root/kh/docker-compose.yml' is invalid because:
Unsupported config option for services.redis: 'sysctls'
services.webapi.depends_on contains an invalid type, it should be an array
services.proxy.depends_on contains an invalid type, it should be an array
services.frontend.depends_on contains an invalid type, it should be an array
Traceback (most recent call last):
  File "./ambar.py", line 283, in <module>
    install(configuration)
  File "./ambar.py", line 202, in install
    pullImages(configuration)
  File "./ambar.py", line 134, in pullImages
    runShellCommandStrict("docker-compose -f {0}/docker-compose.yml pull".format(PATH))
  File "./ambar.py", line 64, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker-compose -f /root/kh/docker-compose.yml pull' returned non-zero exit status 1.

so before I go through the uninstall/clean and install the recomened version - is there a difference between your recommended versions and the latest one I installed that would cause this problem????

cheers

Kevin

**Comment by sochix** [comment]
@kevin939 please send your docker and docker-compose versions

**Comment by kevin939** [comment]
Hi, just (re)installed docker-compose.....

docker-compose version 1.20.0-rc2, build 8c4af54
Docker version 17.12.1-ce, build 7390fc6

so tried again........and it looks like it worked. So the error previously looks like it was associated with not having docker-compose installed

onward........

cheers


Kevin
