### ISSUE TITLE
ambar.py install error

### ISSUE THREAD

**Issue by itnoreplymax** [RD17/ambar#138]
HI,
  I execute this command sudo ./ambar.py install after alll file are download am getting error like no such a file found /etc.rc.local..
[](url)
![error ambar](https://user-images.githubusercontent.com/34542563/37518990-9596601e-293d-11e8-874a-250325608b7d.png)

**Comment by jimoquinn** [comment]
What version and distro of Linux are you using?  It can't find the /etc/rc.local file which is causing the error.

**Comment by hbh7** [comment]
Pretty sure I had the same issue on Ubuntu 17.10

**Comment by sochix** [comment]
Closing, as on the latest Ambar version ambar.py is removed
