### ISSUE TITLE
Setting up SMB crawler -> Error: undefined

### ISSUE THREAD

**Issue by TrailerTracch** [RD17/ambar#14]
Attempting to setup the SMB crawler following the guide in the blog.  Problem is I keep getting this red message at the bottom saying Error: undefined.  There are no "i" markers on the left or highlighting to tell me where this may be or what it means.  Below is my config with some slight edits.

Edits made: IP address, location, login, and password. 

{
  "id": "Share",
  "description": "Share HDD",
  "type": "smb",
  "locations": [
    {
      "host_name": "EDITED",
      "ip_address": "192.168.1.xxx",
      "location": "EDITED"
    }
  ],
  "file_regex": "(\\.doc[a-z]*$)|(\\.xls[a-z]*$)|(\\.txt$)|(\\.csv$)|(\\.htm[a-z]*$)|(\\.ppt[a-z]*$)|(\\.pdf$)|(\\.msg$)|(\\.zip$)|(\\.eml$)|(\\.rtf$)|(\\.md$)|(\\.png$)|(\\.bmp$)|(\\.tif[f]*$)|(\\.jp[e]*g$)",
  "credentials": {
    "auth_type": "ntlm",
    "login": "EDITED",
    "password": "EDITED"
    
  },
  "schedule": {
    "is_active": true,
    "cron_schedule": "*/15 * * * *"
  },
  "max_file_size_bytes": 30000000,
  "verbose": true
}

Could the issue be related to the location?  I've tried:
"\\COMPUTERNAME\SHARE"
"//COMPUTERNAME/SHARE"
"SHARE"

**Comment by sochix** [comment]
Hello @TrailerTracch !

Please, add field `token` to `credentials` object with empty string value.
It should look like this:

```
"credentials": {
  "auth_type": "ntlm",
  "login": "EDITED",
  "password": "EDITED"
  "token": ""
},
```

We fixed the error message, run `sudo ./ambar.py update` to get the fix
We also updated docs: [Crawling Your Own Shared Folders](https://blog.ambar.cloud/advanced-ambar-usage-crawling-your-own-shared-folders/)

**Comment by TrailerTracch** [comment]
EDIT

I fiddled around with it and it worked!  Not sure what I was doing wrong but we are good.  Thank you very much.

For the record my location is setup as the following in case anyone else has an issue:
"location": "FOLDERNAME"


Thanks for the quick reply and fix!  I see now in the screenshot I overlooked the token part.

I have the crawler setup but now I'm stuck at the following:
[info] filecrawler initialized
[error] error connecting to Smb share on PCNAME

I've double checked my account for ambar to access this share but is there anyway to get a more detailed logging on this to figure it out?

**Comment by isido993** [comment]
It's quite strange, because in case of smb connection error you should get two lines in the log, like this:
```
2017-04-13 11:10:00.964: [info] filecrawler initialized
2017-04-13 11:11:00.999: [error] timed out
2017-04-13 11:11:01.007: [error] error connecting to Smb share on DESKTOP-2FHRAM
```

`location` field must start with the share name you're going to crawl, e.g. `"location": "Share/EnglishStories"` or `"location": "Share"`. Have you checked you host name/IP address, also did you try to access your share manually via windows explorer?

**Comment by TrailerTracch** [comment]
@fpd4444 
Share access via windows explorer was fine along with the IP,name, and account.  I believe I just didn't have the other parts of the config correct.  I appreciate everyone's help with this and getting me up and running!

**Comment by sochix** [comment]
@TrailerTracch is problem solved? Can I close the issue?

**Comment by sochix** [comment]
Closing issue. No response from issue author
