### ISSUE TITLE
Reg: I can't upload a file

### ISSUE THREAD

**Issue by itnoreplymax** [RD17/ambar#140]
Hi ,
  I configured amabar GPC. My gps server  ip was http://35.231.87.23. I uploaded files past weeks. Now am tried to upload files it's shows error. Here attached screen shot for your reference. 
**"oops something went wrong. Please reload the site"**
![amabar file upload error](https://user-images.githubusercontent.com/34542563/37963986-9ccc0d72-31dd-11e8-987e-89b5947436c9.png)

I uploaded 17Kb file but am got mentioned error

**Comment by itnoreplymax** [comment]
I uploaded 17Kb file but am got mentioned error  above

**Comment by sochix** [comment]
@itnoreplymax share your webapi logs with us. please

**Comment by itnoreplymax** [comment]
[config_json.txt](https://github.com/RD17/ambar/files/1863974/config_json.txt)

Hi,
  I can't create any crawler in our server. I modified IP Address only. Here i will attached my server syslog,authlog & cofig.json. Please suggest with us
[syslog.txt](https://github.com/RD17/ambar/files/1863962/syslog.txt)
[amar server auth log.txt](https://github.com/RD17/ambar/files/1863964/amar.server.auth.log.txt)


I tried to find out webapi but i can't  ambar. can you share a path

**Comment by sochix** [comment]
Try the latest Ambar version or request [our paid support](https://github.com/RD17/ambar#support)
