### ISSUE TITLE
Cannot start Ambar ('container ... is unhealthy')

### ISSUE THREAD

**Issue by jvdb99** [RD17/ambar#143]
Hello,

Unfortunately I cannot start Ambar. I receive the following error message after the "$  sudo ./ambar.py start" command:

> ______           ____     ______  ____
> /\  _  \  /'\_/`\/\  _`\  /\  _  \/\  _`\
> \ \ \L\ \/\      \ \ \L\ \ \ \L\ \ \ \L\ \
>  \ \  __ \ \ \__\ \ \  _ <'\ \  __ \ \ ,  /
>   \ \ \/\ \ \ \_/\ \ \ \L\ \ \ \/\ \ \ \ \
>    \ \_\ \_\ \_\ \_\ \____/ \ \_\ \_\ \_\ \_\
>     \/_/\/_/\/_/ \/_/\/___/   \/_/\/_/\/_/\/ /
> 
> 
> 
> Docker version 18.03.0-ce, build 0520e24
> docker-compose version 1.18.0, build 8dd22a9
> vm.max_map_count = 262144
> net.ipv4.ip_local_port_range = 15000 61000
> net.ipv4.tcp_fin_timeout = 30
> net.core.somaxconn = 1024
> net.core.netdev_max_backlog = 2000
> net.ipv4.tcp_max_syn_backlog = 2048
> vm.overcommit_memory = 1
> ambar_db_1 is up-to-date
> ambar_redis_1 is up-to-date
> ambar_rabbit_1 is up-to-date
> ambar_es_1 is up-to-date
> 
> ERROR: for webapi  Container "947e5be6ee8f" is unhealthy.
> ERROR: Encountered errors while bringing up the project.
> Traceback (most recent call last):
>   File "./ambar.py", line 264, in <module>
>     start(configuration)
>   File "./ambar.py", line 209, in start
>     runShellCommandStrict('docker-compose -f {0}/docker-compose.yml -p ambar up -d'.format(PATH))
>   File "./ambar.py", line 64, in runShellCommandStrict
>     subprocess.check_call(command, shell = True)
>   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command 'docker-compose -f /home/ubuntu/docker-compose.yml -p ambar up -d' returned non-zero exit status 1

I did the following:
1. Set up an EC2 instance via AWS -- Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-7c412f13
2. Installed Docker CE based on this guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
3. Installed Docker-compose based on this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-16-04
4. Installed Ambar using the guide here: https://blog.ambar.cloud/ambar-installation-step-by-step-guide-2/

I noticed two similar reported issues...
https://github.com/RD17/ambar/issues/99
https://github.com/RD17/ambar/issues/110
...but I am afraid I am not skilled enough to derive any solutions from these reported issues.

Who knows how to solve my issue? Thanks in advance!

Greets, J.vd.B.

**Comment by sochix** [comment]
Try the latest version, check the installation instruction here https://github.com/RD17/ambar/blob/master/Install.md

**Comment by cedricwalter** [comment]
find container not starting and its CONTAINER_ID
`docker ps`
and run 
`docker logs CONTAINER_ID`
to find the issue,

**Comment by sochix** [comment]
No answer from issue opener
