### ISSUE TITLE
Tag by folder name?

### ISSUE THREAD

**Issue by hbh7** [RD17/ambar#145]
Hey,

Is it possible to add tags based on the folder name (likely at import time)?
Ex: Files in folder "12th Grade Physics" could automatically receive a tag with the same name. 

It would also be neat if there could be a way to custom parse the folder name.
Ex: "Files in folder "12th Grade Physics" could also receive the tags "12th Grade" and "Physics" 

Thanks

**Comment by sochix** [comment]
Yep, it can be done with custom automatic tagging rules

**Comment by hbh7** [comment]
Is there documentation on how to set this up somewhere?

**Comment by sochix** [comment]
You can start by exploring pipeline [here](https://github.com/RD17/ambar/tree/master/Pipeline), we do not have any docs as for now
