### ISSUE TITLE
Running Ambar on a USB

### ISSUE THREAD

**Issue by kctdfh** [RD17/ambar#146]
If I install Ubuntu on a live USB and install Ambar on that USB, and then analyze my DropBox files, can I take that USB to another computer and still have all my tags and processed documents? This could help us stay private, collaborate asynchronously, and avoid having to set up authentication. 

Is this possible?

**Comment by sochix** [comment]
For sure I don't know, we didn't have such case

**Comment by denis1482** [comment]
Ambar seems to store all it's data inside ${dataPath}, so if you configure it to be on a USB drive, it should become portable.
