### ISSUE TITLE
static.ambar.cloud/ambar.py off?

### ISSUE THREAD

**Issue by noviceiii** [RD17/ambar#148]
Dear all

Thanks for that fantastic piece of Software.

I was on to update my installation but I bricked it.
I can't re-install/ update as I get an SSL error and a 404 (not found) for https://static.ambar.cloud/ambar.py.

Maybe I am doing something wrong or your host indeed has an issue(?).

Kind Regards
n3

**Comment by sochix** [comment]
We changed the installation process, please read https://github.com/RD17/ambar/blob/master/Install.md

**Comment by noviceiii** [comment]
that was indeed a quick answer!
Thanks. I'll follow the new procedure.
