### ISSUE TITLE
API not returning JSON in version 2rc

### ISSUE THREAD

**Issue by bc2m** [RD17/ambar#151]
We did a clean install of the new version 2.0rc.  Now the REST API is returning html and not JSON.  Can anyone please advise how to access the REST API in the latest release?  It used to be like:

192.168.0.46/api/search?query=

Can someone please help / advise?

Barry

**Comment by bc2m** [comment]
The API for JSON is on port 8080 now.  So http://192.168.0.46:8080/api/search?query=  works and returns JSON

**Comment by syonip** [comment]
Maybe document this somewhere?
