### ISSUE TITLE
API-search with size parameter returns false amount of results

### ISSUE THREAD

**Issue by thieren** [RD17/ambar#152]
Hey there,

i'm still on 1.2 but can't upgrade just yet, because a clean install is necessary.

That said, if i do an api-search (e.g. http://ambarip/api/search?query=*&size=10) then i get a result-JSON with 20 hits (on the first page). If i do this with size=3 then i get 6 hits and so on.

This continues on page 2, 3 until at a varying page it returns to  the default behaviour (e.g. size=3 and returns 3 hits). On which site the standard behaviour starts depends on the search term.

I assume that this is a bug. Can anyone tell me if this is adressed in newer versions?

Thanks in advance!

**Comment by sochix** [comment]
@Thieri85 hi, it is not a bug. We perform two search queries each time, First for small files and second for large files, that's why you got different number of results. We plan to replace two queries with one in the feature, but to do it we need to develop some new way to handle large files in ES.

**Comment by thieren** [comment]
Ok, at least this explains the issue.

But this brings me to the next question: is there a way to determine the total number of pages for a given query? I would need this information for my use case because i'd like to let the user navigate to specific pages of a search result.
