### ISSUE TITLE
Standalone or cross-platform

### ISSUE THREAD

**Issue by javadevelopernextgen** [RD17/ambar#155]
It would be nice if the application can work as standalone or has cross-platform exes for windows, mac, linux and other OS.

**Comment by sochix** [comment]
You can run Ambar as standalone application on your own server, also you can distribute Ambar as VM image. Ambar can not be compiled to exec as it has a lot of external dependecies and also designed to work as a server side software.

**Comment by smartdeveloper2018** [comment]
Is it possible to document the steps  with screenshots on how to deploy the Ambar in a server in a fresh windows and linux box?

**Comment by sochix** [comment]
@smartdeveloper2018 yep, but we have no time to do it, if you want you can help us. Start from [Installation guide](https://github.com/RD17/ambar/blob/master/Install.md)
