### ISSUE TITLE
Exclude certain directories while performing search

### ISSUE THREAD

**Issue by sufiyanghori1** [RD17/ambar#156]
Hello,
I just went through,
https://blog.ambar.cloud/mastering-ambar-search-queries/

but couldn't find a way to exclude certain file type or a directory from result.

Is there any way to do so yet?

**Comment by sochix** [comment]
Nope, it can't be done via query. But you can exclude files during crawling. Check the latest installation instruction

**Comment by denis1482** [comment]
You can set ignoreFolders, ignoreExtensions, ignoreFileNames options in your crawler's environment section in .yml-file
