### ISSUE TITLE
Sync Ambar to remove file from ambar_file_data, when original file is removed

### ISSUE THREAD

**Issue by sufiyanghori1** [RD17/ambar#157]
Hi,
right now, Ambar deduplicates all the files from the path provided to a crawler, However when the file is removed from the original directory, it is still available to ambar, and had to be manually removed from front-end.

Is there a way to make sure file is removed from Ambar file data when it is removed from its cralwer path?

**Comment by sochix** [comment]
It's done in the latest relase (v2.1.8)
