### ISSUE TITLE
slow crawl

### ISSUE THREAD

**Issue by denis1482** [RD17/ambar#158]
When crawling a large storage (100k+ docx/xlsx files) on cifs-mounted share, 2.0.0rc performs very poor, adding less than 50 files per day. Ubuntu 18.04 64-bit, lots of RAM and CPUs.

**Comment by sochix** [comment]
Please update Ambar, we improved the prefomance. Also you should tune docker-compose to give ES as much RAM as you can and add 2-3 pipelines.

**Comment by denis1482** [comment]
Fixed in 2.1.8
