### ISSUE TITLE
branding, removing upload

### ISSUE THREAD

**Issue by cedricwalter** [RD17/ambar#159]
I've check the code, but it would be nice to have a config entry to remove the upload button when not deployed on intranet (as there is no login) 

currently and when Ambar is deployed on Internet, anybody can start uploading pdf and do a DOS by filing up the filesystem..

Can you help?

**Comment by cedricwalter** [comment]
i've found a (bit ugly) workaround i think

start container
`docker-compose up -d`

copy resources to a local folder
`docker cp CONTAINER_ID:/usr/share/nginx/html/. /home/ambar/frontend/html/
`
stop container and add a new volume to frontend
`docker-compose stop`

in docker-compose.yml
```
volumes:
      - /home/ambar/frontend:/usr/share/nginx/html
```

restart
now i can change css and logo in `/home/ambar/frontend`

I would prefer to be able to use variables in docker-compose as this method has lot of drawback
* at each update of Ambar, the css has to be manualy merged 
* this is a kind of hack, somebody can reactivate the upload button and or directly send request to the API

**Comment by sochix** [comment]
Hello @cedricwalter ,
please do not remove branding as it an only way to say "Thanks" to developers team that bring Ambar to life. 

To disable file uploading you can set up "basic_auth" on nginx. 

Also you can ask us to do any custom feature development
