### ISSUE TITLE
Run Ambar Search without Docker

### ISSUE THREAD

**Issue by petrk94** [RD17/ambar#163]
Hello,

I would like to use Ambar Search, but on my Server I cant run docker.
Is a alternative possible?

**Comment by sochix** [comment]
It's impossible

**Comment by petrk94** [comment]
@sochix nothing is impossible (Toyota ©), how you had made Ambar in the pre-docker era?

**Comment by sochix** [comment]
@petrk94 I just will not start creating Ambar in pre-docker era. It's not the topic for discussion, Ambar works ONLY with docker. That's it.
