### ISSUE TITLE
Feature Request: Show sidebar on small screens

### ISSUE THREAD

**Issue by chrisl8** [RD17/ambar#165]
The sidebar on the left is not visible at all in the mobile view, or even if you just have a narrow view.

This prevents use of the Table View unless you have the browser window open wide enough on a desktop.

Perhaps the left sidebar menu could move to the top in mobile, or tapping the owl image could open it up?

**Comment by sochix** [comment]
Hello,
yep sidebar is hidden on small screens.

If you want for additional fee we can add this to our next sprint.
