### ISSUE TITLE
No crawler options in Settings page

### ISSUE THREAD

**Issue by svetsch** [RD17/ambar#168]
Hi,

First thanks for your great project, I found it really clear and well structured.

I'm trying to follow the instructions of the page:
https://blog.ambar.cloud/crawling-and-searching-email-inbox-with-ambar/

But with my fresh install, the document processing is working fine, but the settings page only displays the logs and there is no options related to crawlers.

Is there anything that I may have missed ?

**Comment by sochix** [comment]
Hi @svetsch 
From version 2.0, Ambar supports only local fs crawling. So the article is outdated. Now it's unpublished. Sorry for inconvenience.
