### ISSUE TITLE
Github repository for Webapi and Pipeline

### ISSUE THREAD

**Issue by morloy** [RD17/ambar#17]
I am trying to get Ambar running on OSX.
It works so far, however the pipeline seems to be not able to connect to the Rabbit server. Thus, no documents are being processed and nothing is added to the search index.

I am trying to understand what's going on behind the scenes in order to find a solution for this problem. Unfortunately, the code for the Webapi and Pipeline docker images are not public.

Do you plan to release these soon?

**Comment by isido993** [comment]
We're working on it, separating CE and EE editions code is a quite tricky thing to do.

Could you post your `docker-compose.yml` here? Maybe I'll be able to solve your issue.

**Comment by morloy** [comment]
Thanks for the quick reply! Finally, I found that setting the host to 127.0.0.1 doesn't work in the docker environment. Using the IP from my wifi interface solves the problem and everything is running so far.

**Comment by andychoi** [comment]
Without reviewing Webapi and Pipeline docker images as IT security requirement, it is impossible to adapt EE edition. I hope two missing docker images become open-sourced.

**Comment by sochix** [comment]
@andychoi hello, we can give you direct accesss to a source code for reviewing after purchasing EE
