### ISSUE TITLE
WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.

### ISSUE THREAD

**Issue by hardnottolook** [RD17/ambar#176]
When executing _docker logs --follow docker_ambar_pipeline0_1_ I receive the following two errors:

> Aug 07, 2018 8:20:47 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
> WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
> See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
> for optional dependencies.

> Aug 07, 2018 8:20:47 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
> WARNING: Tesseract OCR is installed and will be automatically applied to image files unless
> you've excluded the TesseractOCRParser from the default parser.
> Tesseract may dramatically slow down content extraction (TIKA-2359).
> As of Tika 1.15 (and prior versions), Tesseract is automatically called.
> In future versions of Tika, users may need to turn the TesseractOCRParser on via TikaConfig.
> Aug 07, 2018 8:20:47 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
> WARNING: org.xerial's sqlite-jdbc is not loaded.
> Please provide the jar on your classpath to parse sqlite files.
> See tika-parsers/pom.xml for the correct version.

I've already tried the mentioned links [https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io](url) and [tika-parsers/pom.xml)](url) but without any success.

Since it seems that no one has had this problem so far, help would be much appreciated. Thanks!

**Comment by musical10441** [comment]
I actually see this as well.
