### ISSUE TITLE
[pipeline] [info] [0] error extracting pst, code: 139

### ISSUE THREAD

**Issue by musical10441** [RD17/ambar#178]
Good morning:

I'm attempting to process a small (265KB) PST using the default Images and receive the following error message:

**Log file in the web front end:
[pipeline] [info] [0] error extracting pst, code: 139**

**Pipeline log:
Segmentation fault (core dumped)**

Full pipeline file: 

> Opening PST file and indexes...
> Processing Folder "Deleted Items"
> Processing Folder "Inbox"
> Processing Folder "McAfee Anti-Spam"
>         "Inbox" - 4 items done, 2 items skipped.
> Processing Folder "Outbox"
> Processing Folder "Sent Items"
>         "Sent Items" - 5 items done, 0 items skipped.
> Processing Folder "Junk E-mail"
> Processing Folder "Conversation Action Settings"
> Processing Folder "Quick Step Settings"
>         "accounts@myvendor.com" - 7 items done, 0 items skipped.
> Segmentation fault (core dumped)
> Opening PST file and indexes...
> Processing Folder "Deleted Items"
> Processing Folder "Inbox"
> Processing Folder "Outbox"
> Processing Folder "Sent Items"
>         "Sent Items" - 1 items done, 0 items skipped.
> Processing Folder "Junk E-mail"
> Processing Folder "Conversation Action Settings"
> Processing Folder "Quick Step Settings"
>         "ann@mystate.local" - 7 items done, 1 items skipped.
> Segmentation fault (core dumped)
> Opening PST file and indexes...
> Processing Folder "Deleted Items"
> Processing Folder "Inbox"
> Processing Folder "Outbox"
> Processing Folder "Sent Items"
> Processing Folder "Calendar"
>         "Calendar" - 0 items done, 3 items skipped.
> Processing Folder "Contacts"
>         "Contacts" - 0 items done, 2 items skipped.
> Processing Folder "Journal"
> Processing Folder "Notes"
> Processing Folder "Tasks"
> Processing Folder "Drafts"
> Processing Folder "RSS Feeds"
> Processing Folder "Conversation Action Settings"
> Processing Folder "Quick Step Settings"
> Processing Folder "Junk E-mail"
>         "Outlook" - 14 items done, 0 items skipped.
> Segmentation fault (core dumped)

**Comment by musical10441** [comment]
Hi - just checking in on this issue.

**Comment by musical10441** [comment]
My developer resolved the issue as follows:


Exit code 139 solved :
It was due to memory bug in OS/readpst code. (ref https://groups.google.com/forum/#!topic/omnetpp/_zonGWenUqg)
Pipeline docker container was using old debian version OS, so we changed it to 
ubuntu:16.04 (changed in file Pipeline/Dockerfile)

**Comment by sochix** [comment]
@musical10441 made a PR please with your changes
