### ISSUE TITLE
Seriviceapi Error while docker-compose up

### ISSUE THREAD

**Issue by tushar21** [RD17/ambar#186]
I am having error while docker compose up : ERROR: for serviceapi  Container  "e6a3e3b4cef9" is unhealthy.

**Comment by steve-boyle** [comment]
I would say, run `sudo docker ps` to get the instance name for the serviceapi container.  The name is going to be something like username_serviceapi_1.
Then run `sudo docker logs username_serviceapi_1`, obviously you want to use your proper instance name there.  Hopefully, you can figure out your issue from the log.

**Comment by tushar21** [comment]
I can't find the root cause but got the temporary solution. After clearing the datastore, serviceapi is working again.
