### ISSUE TITLE
Error when starting up ambar (serviceapi  Container is unhealthy)

### ISSUE THREAD

**Issue by ratio91** [RD17/ambar#189]
Creating docker-ambar_redis_1  ... done
Creating docker-ambar_es_1     ... done
Creating docker-ambar_rabbit_1 ... done
Creating docker-ambar_db_1     ... done

**ERROR: for serviceapi  Container "16d637ef76b6" is unhealthy.**
ERROR: Encountered errors while bringing up the project.

anyone else ever encountered this error?
it worked like a charm over the summer, only when I recenctly updated the images this happens.
Please help, thank you!

**Comment by isido993** [comment]
Hello,

Run 'docker ps -a', find a container with 'exited' state, and then run 'docker logs <name of the exited container>' and post the results here.

Also, could you share the business issue you're solving/trying to solve with Ambar with me? It'll help us develop it into a better product. Thanks.

**Comment by ratio91** [comment]
I solved it by setting ES memory to:
`sudo sysctl -w vm.max_map_count=262144`

I use ambar for searching PDF and MS Word Documents (CVs) and improving full-text search for users.

**Comment by asittampalam** [comment]
Hey guys. First of all thanks for your great work!
I face the same issue ratio91 did - I'm on Mac OSX though (dev system). But even using 
`screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty` 
to set 
`sysctl -w vm.max_map_count=262144
sysctl -w net.ipv4.ip_local_port_range="15000 61000"
sysctl -w net.ipv4.tcp_fin_timeout=30
sysctl -w net.core.somaxconn=1024
sysctl -w net.core.netdev_max_backlog=2000
sysctl -w net.ipv4.tcp_max_syn_backlog=2048
sysctl -w vm.overcommit_memory=1`
doesn't solve the issue for me. Any hints? Thanks.
