### ISSUE TITLE
Feature Request: Chinese (Simplified and Traditional) and Japanese Language Analyzer

### ISSUE THREAD

**Issue by mspencer08** [RD17/ambar#19]
Hi there,

I found this great app on reddit and am trying it out, both on your public cloud and on local dev machine using docker. Now I 'd like to ask if you can add the language analyzer for Chinese (Simplified and Traditional) and Japanese? 

The CJK are some tricky languages to deal with and here's what I found on stackoverflow regarding the Chinese and Japanese language analyzers: http://stackoverflow.com/questions/29098347/elasticsearch-cjk-language-analyser. Sadly there isn't one for Korean yet. 

I also want to curious about how well the current Tesseract OCR tuning included in ambar works with CJK languages.

Thanks.

**Comment by sochix** [comment]
Done
