### ISSUE TITLE
Downloading a file from a search result

### ISSUE THREAD

**Issue by Triangulum9r** [RD17/ambar#190]
Is it possible to download or export a file after it has been indexed and uploaded?

**Comment by jerome83136** [comment]
interresting in the same question
+1

**Comment by isido993** [comment]
Hello everyone!
You can only download files crawled from mounted fs, you can't download uploaded files since the originals are not stored in Ambar.

Also, could you share the business issue you're solving/trying to solve with Ambar with me? It'll help us develop it into a better product. Thanks.
