### ISSUE TITLE
Supported languages

### ISSUE THREAD

**Issue by jerome83136** [RD17/ambar#191]
Hi,

Could you tell me if the French language is supported ?

In the latest README (15 days ago); it seems it is not is the list: https://raw.githubusercontent.com/RD17/ambar/master/README.md

But on the main Github page, it is written:

> Which languages are supported for OCR?
> 
> Supported languages: Eng, Rus, Ita, Deu, Fra, Spa, Pl, Nld. If you miss your language please contact us on hello@ambar.cloud.

It seems the French (Fra) is supported.

Could you confirm ?

Thanks
Best regards

**Comment by isido993** [comment]
Hello!
It's not supported at the moment, but you can add it to ServiceApi/src/services/EsProxy/AmbarFileDataMapping.json file in ES mappings (as 'ambar_fr').

By the way, could you share the business issue you're solving/trying to solve with Ambar with me? It'll help us develop it into a better product. Thanks.
