### ISSUE TITLE
 './docker-compose.yml' is invalid because:

### ISSUE THREAD

**Issue by gerroon** [RD17/ambar#197]
Trying to run it on Deb testing

The install doc here does not mention antyhing about crawlername
https://ambar.cloud/docs/installation/

compose file
https://paste.debian.net/hidden/2b8c96ef/

 docker-compose pull
WARNING: The dataPath variable is not set. Defaulting to a blank string.
WARNING: The crawlerName variable is not set. Defaulting to a blank string.
WARNING: The pathToCrawl variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid service name '${crawlerName}' - only [a-zA-Z0-9\._\-] characters are allowed

**Comment by gerroon** [comment]
Ok in the next link there is something about it

But I still do not understand what I am supposed to do. Is this a custom name or some special name? What is a service block name? 

thanks

**Comment by itnoreplymax** [comment]
Hi,
   I have checked with your file it's default settings. Here ${dataPath}means your  local storage volume mount path.
Here crawlerName means like block name(FTP Storage,S3 & SMB), environment name and block name are should be same. Suppose it will be change ambar not working, pathToCrawl=storage path for pathToCrawl(like FTp,SMb & S3 bucket).

Here am attached file for your reference. Proceed with same stpes.
[Set.1-Craweling.for.local.storage.1.docx](https://github.com/RD17/ambar/files/2530507/Set.1-Craweling.for.local.storage.1.docx)

Note:Red Color mentioned lines- changed environment it's working good

**Comment by gerroon** [comment]
@itnoreplymax thanks I will take a look at it. Thanks for the the doc.
