### ISSUE TITLE
Question: Why are you using ES 5.6?

### ISSUE THREAD

**Issue by AyKarsi** [RD17/ambar#201]
.. and any plans to upgrade to 6.x? 

Great tool btw!

**Comment by sochix** [comment]
@AyKarsi what features did you miss? why we should update es to 6.x?

**Comment by DragonPulse** [comment]
had difficulties in ambar/ambar-es 
not able to start that docker , everything looks good

**Comment by AyKarsi** [comment]
@sochix was a question out of curiosity. I'm not missing any features.

**Comment by isido993** [comment]
@DragonPulse Take a look at [https://ambar.cloud/docs/installation/#set-up-your-environment](https://ambar.cloud/docs/installation/#set-up-your-environment)

**Comment by isido993** [comment]
@AyKarsi "elasticsearch-analysis-morphology" plugin does not support 6.x. So we can't directly switch to 6.x since we'd have to modify our russian lang. analyzer and switch it to Hunspell token filter. This requires additional tuning and testing. We'll do it in future, but not now.
