### ISSUE TITLE
How are the results ordered?

### ISSUE THREAD

**Issue by s1rk1t** [RD17/ambar#203]
Just wondering what determines the order of the results returned by AMBAR's search feature?

**Comment by sochix** [comment]
Hi, we use ES results order

**Comment by s1rk1t** [comment]
Thanks for the quick response! Do you happen to know how ES determines the order they use? I can't find any rhyme or reason in the ordering.

**Comment by sochix** [comment]
Can't help, check their docs

**Comment by s1rk1t** [comment]
Ok, thanks
