### ISSUE TITLE
how to change color of search bar

### ISSUE THREAD

**Issue by s1rk1t** [RD17/ambar#204]
Hi all,

I've used the inspect tool and see that it's background-color value for the search bar div is rgb(0, 188, 212) but have grepped the entire file system, but for the life of me can't find any div with that background-color value. I also tried grepping with the corresponding hex color value with no success. Any one have any idea where the search bar background color value is being set?

Thanks in advance for any help you can offer.

**Comment by sochix** [comment]
Set the style here https://github.com/RD17/ambar/blob/master/FrontEnd/src/layouts/MainLayout/MainLayout.js line 44

**Comment by s1rk1t** [comment]
Thanks!
