### ISSUE TITLE
How to remove tag

### ISSUE THREAD

**Issue by s1rk1t** [RD17/ambar#206]
So I discovered a setting in the SideMenu.js file (line 75) that toggles whether to show a 'remove icon' on the tags, but after setting it to true, when I click on it, nothing happens. 

What do I need to do in order to remove a tag?

**Comment by isido993** [comment]
Do you mean removing a tag from the side panel directly?
If so - you can't do that, this would mean removing it from all files tagged with it, and there's no such method in the api. You can add this method yourself (you'll have to call delete by query in the ES).

**Comment by s1rk1t** [comment]
Thanks for the response. 

I found a workaround which entailed me changing the location of the data being crawled and (not sure this next step was necessary) clearing the images and then redownloading them all before spinning up another instance of AMBAR. 

That got me back to the original state where no tags had yet to be applied, which will suit my purposes for now.
