### ISSUE TITLE
How to add scrolling to the side menu

### ISSUE THREAD

**Issue by s1rk1t** [RD17/ambar#207]
So I looked around and there is a class in the SideMenu.scss file called '.container' that I was hoping if I added an attribute: `overflow-y:scroll` would then allow for the menu to be scrollable, but that didn't work. 

Any idea how I can make the side menu scrollable? Is there some container around the one listed in the SideMenu.js file that one might customize to allow for that?

EDIT: I found this: https://github.com/react-toolbox/react-toolbox/issues/218 , and per their recommendation am going to try overflow-y: auto and see if that helps. 

EDIT2: Unfortunately, adding the class attribute 'overflow-y:auto' didn't help. Interested to hear any thoughts on how to accomplish adding scrolling to the side menu, as some items become hidden if the screen is too small to accommodate all of the side menu's content.

**Comment by isido993** [comment]
@s1rk1t 
Add ```overflow-y: auto;``` here: [https://github.com/RD17/ambar/blob/ecb0294a34c0a9a98ccf4efc47fe1311ef50d9db/FrontEnd/src/components/Search/Search.js#L79](https://github.com/RD17/ambar/blob/ecb0294a34c0a9a98ccf4efc47fe1311ef50d9db/FrontEnd/src/components/Search/Search.js#L79)

**Comment by s1rk1t** [comment]
That worked, thank you!

Just in point of reference for anyone else who needs this done:
Due to the React syntax the page is programmed with, the style must read 

overflowY: 'auto',

in order for it to work properly.

Thanks again!
