### ISSUE TITLE
IP address necessary for rendering FrontEnd?

### ISSUE THREAD

**Issue by s1rk1t** [RD17/ambar#208]
Wondering if it's possible to have AMBAR's docker .yml file have something other than the ip address for where the FrontEnd is hosted?

For instance, is there some way I can have line 113 of the .yml file read:
       `- api=http://somedomain/ambar` instead of `-api=http://ipaddress:portnumber` ?

**Comment by Jachimo** [comment]
I was likewise surprised by this. It looks like that line specifies the connection between the web frontend and the API container, which could be done over the Docker internal network? Unless there are other components that need to hit the API besides the web frontend, it seems like you could just use the internal network and specify the container name. But maybe I'm missing something; I have not stopped my instance to test it.

**Comment by isido993** [comment]
@Jachimo you can't use the Docker internal network since the front end always runs in user's browser which is never inside the Docker net.
