### ISSUE TITLE
how to delete file from MongoDB?

### ISSUE THREAD

**Issue by biy-gxnn** [RD17/ambar#210]
how to delete file from MongoDB when i don't want to search this file

**Comment by isido993** [comment]
@biy-gxnn MongoDB is used for storing thumbnails and in some cases for storing original files data. ES is used for searching, so you have to remove the file from the index or mark it as deleted in the UI.
![image](https://user-images.githubusercontent.com/12730310/50823278-a6e15580-1344-11e9-85ae-1a5c3ce01e00.png)
