### ISSUE TITLE
Turn of OCR / Index IPTC/EXIF Info

### ISSUE THREAD

**Issue by robbymeier** [RD17/ambar#216]
Is it possible to turn off OCR and instead have it index the IPTC/EXIF information within image files? Or even better, for REST calls tell it if it  should to OCR or not.

**Comment by ohnx** [comment]
I haven't found a way to selectively disable OCR, but if you add an environment variable in `ambar/ambar-pipeline:latest` as `ocrPdfMaxPageCount=0`, you can disable OCR for all of the files.
