### ISSUE TITLE
Problem with crawler

### ISSUE THREAD

**Issue by Pex16** [RD17/ambar#217]
Hi guys, I have a problem with the crawler of Ambar.
It is similar to that
https://github.com/RD17/ambar/issues/162
but the solution doesn't solve my problem, because I have set correctly the volume path of the crawler.

This is my docker-compose.yml

> version: "2.1"
> networks:
>   internal_network:
> services:      
>   db:
>     restart: always
>     networks:
>       - internal_network
>     image: ambar/ambar-mongodb:latest
>     environment:
>       - cacheSizeGB=2
>     volumes:
>       - /home/ubuntu/Ambar-Cloud/db:/data/db
>     expose:
>       - "27017"   
>   es:
>     restart: always
>     networks:
>       - internal_network
>     image: ambar/ambar-es:latest
>     expose:
>       - "9200" 
>     environment:
>       - cluster.name=ambar-es
>       - ES_JAVA_OPTS=-Xms2g -Xmx2g
>     ulimits:
>       memlock:
>         soft: -1
>         hard: -1  
>       nofile:
>         soft: 65536
>         hard: 65536
>     cap_add:
>       - IPC_LOCK
>     volumes:
>       - /home/ubuntu/Ambar-Cloud/es:/usr/share/elasticsearch/data
>   rabbit:
>     restart: always
>     networks:
>       - internal_network
>     image: ambar/ambar-rabbit:latest
>     hostname: rabbit
>     expose:
>       - "15672"
>       - "5672"   
>     volumes:
>       - /home/ubuntu/Ambar-Cloud/rabbit:/var/lib/rabbitmq
>   redis:
>     restart: always
>     sysctls:
>       - net.core.somaxconn=1024
>     networks:
>       - internal_network
>     image: ambar/ambar-redis:latest
>     expose:
>       - "6379" 
>   serviceapi:
>     depends_on:
>       redis:
>         condition: service_healthy
>       rabbit:
>         condition: service_healthy
>       es:
>         condition: service_healthy
>       db:
>         condition: service_healthy
>     restart: always
>     networks:
>       - internal_network
>     image: ambar/ambar-serviceapi:latest
>     expose:
>       - "8081"  
>     environment:            
>       - mongoDbUrl=mongodb://db:27017/ambar_data
>       - elasticSearchUrl=http://es:9200
>       - redisHost=redis
>       - redisPort=6379
>       - rabbitHost=amqp://rabbit
>       - langAnalyzer=ambar_it   
>   webapi:
>     depends_on:
>       serviceapi:
>         condition: service_healthy
>     restart: always
>     networks:
>       - internal_network
>     image: ambar/ambar-webapi:latest
>     expose:
>       - "8080"
>     ports:
>       - "8080:8080"
>     environment:            
>       - uiLang=en
>       - mongoDbUrl=mongodb://db:27017/ambar_data
>       - elasticSearchUrl=http://es:9200
>       - redisHost=redis
>       - redisPort=6379
>       - serviceApiUrl=http://serviceapi:8081
>       - rabbitHost=amqp://rabbit    
>   frontend:
>     depends_on:
>       webapi:
>         condition: service_healthy
>     image: ambar/ambar-frontend:latest
>     restart: always
>     networks:
>       - internal_network
>     ports:
>       - "80:80"
>     expose:
>       - "80"
>     environment:
>       - api=http://127.0.0.1:8080  
>   pipeline0:
>     depends_on: 
>       serviceapi: 
>         condition: service_healthy                            
>     image: ambar/ambar-pipeline:latest
>     restart: always
>     networks:
>       - internal_network  
>     environment:                
>       - id=0
>       - api_url=http://serviceapi:8081
>       - rabbit_host=amqp://rabbit
>   documents:
>     depends_on: 
>       serviceapi: 
>         condition: service_healthy 
>     image: ambar/ambar-local-crawler
>     restart: always
>     networks:
>       - internal_network
>     expose:
>       - "8082"
>     environment:      
>       - name=documents
>     volumes:
>       - /home/ubuntu/Ambar-Cloud/documents:/usr/data

This is the error reported:

> documents_1  | { RequestError: Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
> documents_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
> documents_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
> documents_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
> documents_1  |   name: 'RequestError',
> documents_1  |   message: 'Error: connect ECONNREFUSED 172.21.0.6:8080',
> documents_1  |    { Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  |   error: 
> documents_1  |    { Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  | (node:6) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
> documents_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
> documents_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
> documents_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
> documents_1  | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> documents_1  | { RequestError: Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
> documents_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
> documents_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
> documents_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
> documents_1  |   name: 'RequestError',
> documents_1  |   message: 'Error: connect ECONNREFUSED 172.21.0.6:8080',
> documents_1  |    { Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  |   error: 
> documents_1  |    { Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  | (node:6) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
> documents_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
> documents_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
> documents_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
> documents_1  | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> documents_1  | { RequestError: Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
> documents_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
> documents_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
> documents_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
> documents_1  |   name: 'RequestError',
> documents_1  |   message: 'Error: connect ECONNREFUSED 172.21.0.6:8080',
> documents_1  |    { Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  |   error: 
> documents_1  |    { Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  | (node:12) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 172.21.0.6:8080
> documents_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
> documents_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
> documents_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
> documents_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
> documents_1  | (node:12) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> ^CERROR: Aborting.

What could be the problem?
`curl 172.21.0.6:8080/api `   doesn't work, the connection is refused.

Thanks for your help or suggestions !

**Comment by denis1482** [comment]
you have
- api=http://127.0.0.1:8080

change it to
- api=http://172.21.0.6:8080:8080

**Comment by Pex16** [comment]
Thank you for your reply.
I tried that fix but it doesn't work.
Now from the log I see this:

> bollettini_1  | { RequestError: Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
bollettini_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
bollettini_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
bollettini_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
bollettini_1  |   name: 'RequestError',
bollettini_1  |   message: 'Error: connect ECONNREFUSED 172.22.0.6:8080',
bollettini_1  |    { Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  |   error: 
bollettini_1  |    { Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  | (node:6) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
bollettini_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
bollettini_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
bollettini_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
bollettini_1  | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
bollettini_1  | { RequestError: Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
bollettini_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
bollettini_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
bollettini_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
bollettini_1  |   name: 'RequestError',
bollettini_1  |   message: 'Error: connect ECONNREFUSED 172.22.0.6:8080',
bollettini_1  |    { Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  |   error: 
bollettini_1  |    { Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  | (node:6) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
bollettini_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
bollettini_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
bollettini_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
bollettini_1  | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
bollettini_1  | { RequestError: Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
bollettini_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
bollettini_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
bollettini_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
bollettini_1  |   name: 'RequestError',
bollettini_1  |   message: 'Error: connect ECONNREFUSED 172.22.0.6:8080',
bollettini_1  |    { Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  |   error: 
bollettini_1  |    { Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  | (node:12) UnhandledPromiseRejectionWarning: RequestError: Error: connect ECONNREFUSED 172.22.0.6:8080
bollettini_1  |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
bollettini_1  |     at Request.onRequestError (/node_modules/request/request.js:878:8)
bollettini_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
bollettini_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
bollettini_1  | (node:12) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by speedmann** [comment]
the docker example seems to be wrong
here is what is working for me
```yaml
  my-files:
    depends_on:
      serviceapi:
        condition: service_healthy
    image: ambar/ambar-local-crawler
    restart: always
    networks:
      - default
    expose:
      - "8082"
    environment:
      - name=my-files
      - ignoreFolders=**/.recycle/**
      - ignoreExtensions=.{exe,dll,rar}
      - ignoreFileNames=*backup*
      - maxFileSize=15mb
      - apiUrl=http://serviceapi:8081
    volumes:
      - /mnt/Backup/drucker:/usr/data
```
see ` - apiUrl=http://serviceapi:8081`
