### ISSUE TITLE
Web API hangs

### ISSUE THREAD

**Issue by thebetterjort** [RD17/ambar#22]
**Error: Web API hangs. Container still shows running.** 
I'm seeing In the browser, "a spinning spinner"

1. VMWare running Ubuntu Xenial 16.04.
2. Kernel 4.4.0-72-generic
3. Docker version 17.03.1-ce, build c6d412e
4. docker-compose version 1.11.2, build dfed245

> docker logs -f ambar-webapi

```
/usr/src/app/dist/services/QueueProxy.js:91
			throw err;
			^

Error: Unexpected close
    at succeed (/usr/src/app/node_modules/amqplib/lib/connection.js:270:13)
    at onOpenOk (/usr/src/app/node_modules/amqplib/lib/connection.js:252:5)
    at /usr/src/app/node_modules/amqplib/lib/connection.js:165:32
    at /usr/src/app/node_modules/amqplib/lib/connection.js:159:12
    at Socket.recv (/usr/src/app/node_modules/amqplib/lib/connection.js:497:12)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:419:10)
    at emitReadable (_stream_readable.js:413:7)
    at readableAddChunk (_stream_readable.js:164:13)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:540:20)
2017/04/17 23:13:42 Command exited with error: exit status 1
```
> docker logs -f ambar-rabbbit
```
=ERROR REPORT==== 17-Apr-2017::23:06:18 ===
closing AMQP connection <0.551.0> (172.19.0.1:36775 -> 172.19.0.4:5672):
missed heartbeats from client, timeout: 60s
```

**Comment by isido993** [comment]
Hello.

Looks like WebApi stops sending heartbeats to Rabbit. It's a quite strange issue, we've not seen this kind of behavior before. What hardware environment are you using? Is it VM or VPS? Maybe VM is being suspended in idle state?

**Comment by sochix** [comment]
@thebetterjort any news?

**Comment by sochix** [comment]
Closing as author did not reply for a week

**Comment by thebetterjort** [comment]
I'm sorry I was out for surgery.

HP DL 380 Hosts we have in the flex pod. 
Storage is a NETapp.

**Comment by isido993** [comment]
Ah, hope you're well now!

Please update your Ambar, we've made a serious networking upgrade that should solve your issue.
Run `wget -O ambar.py https://static.ambar.cloud/ambar.py && chmod +x ./ambar.py`, then run `sudo ./ambar.py update`. After your Ambar is updated you'll have to signup with your email since we've added authentication into Ambar CE.
