### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Pex16** [RD17/ambar#222]
Hi, I have installed and configured Ambar and it works correctly.
The problem is that when I reach the url where it is published I see the search page directly, without authentication. I have seen from other issues that I have to change some settings in _config.json_ file. My problem is that I don't know which _config.json_ I have to edit.
In particular, I have the following _config.json_:

/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_01/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_02/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_03/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_04/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_05/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_06/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_07/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_08/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_09/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_10/config.json
/run/containerd/io.containerd.runtime.v1.linux/moby/container_ID_11/config.json

I have 11 config.json because of I have multiple container that I have mounted with docker-compose(frontend, webapi, es, some crawler, etc.).
Moreover I tried to search in these files if there is the auth option (for example setted to none), but I found nothing.
What changes do I have to do?
Thank you for the help.

**Comment by hitendesai** [comment]
Hi
I'm also trying to implement a login UI before the Ambar dashboard. There is a JSON file called "localizations.json" which has details about login, signup, and password reset. But how do we implement the login UI?

Thanks in advance!

**Comment by naman2407** [comment]
Hi 

I'm also trying to implement a Login UI before the Ambar dashboard. Ambar's UI is fully working on GCP and localhost. I found a file 'localizations.json' which has some information regarding the login, password reset and signup page. But how do we implement the login UI or from where do we have to turn on the login UI?

Thanks in advance!
