### ISSUE TITLE
Oops.... Something went wrong" during loading

### ISSUE THREAD

**Issue by itnoreplymax** [RD17/ambar#225]
Hi,
   I configured ambar today using ubuntu 18.04 lts. After successful installation i load ambar ui in browser.  During loading of the page, I get the error "Oops.... Something went wrong" at the bottom.  Here attached my docker-compose.yml file and docker logs for your reference.
[Docker compose file yml.txt](https://github.com/RD17/ambar/files/2973850/Docker.compose.file.yml.txt)
[ambar log error.txt](https://github.com/RD17/ambar/files/2973851/ambar.log.error.txt)

**Comment by johnkv** [comment]
Hello,
I was troubleshooting my issue and compared your Docker-Compose.yml to mine and noticed you have misspelled ambar (you put ambae) on line 138.  Maybe that is your issue?  (I just discovered this project, it came up and appears to be working for me, will keep testing)

**Comment by itnoreplymax** [comment]
> 
> 
> Hello,
> I was troubleshooting my issue and compared your Docker-Compose.yml to mine and noticed you have misspelled ambar (you put ambae) on line 138. Maybe that is your issue? (I just discovered this project, it came up and appears to be working for me, will keep testing)

Dear John,
   Thanks for the information. I checked my compose file here made mistake for environment setting. Now it's working perfectly. 
I created test.txt under a path /media/Docs:/usr/data but the file not listing on web. The uploaded files are working and indexed it's show UI.
Kindly suggest..
