### ISSUE TITLE
Feature Request: Store Manually Uploaded Files in the Database (for later download)

### ISSUE THREAD

**Issue by simhavaktra** [RD17/ambar#228]
I've seen this question and request kicked around a few times and fizzle out so I figured I'd throw my hat into the ring as well.

We have a number of employees that receive files to their computer from clients and prefer to upload directly via the WebUI rather than into the crawled SMB share. The workflow is great as is the indexing, but the inability to download the file back (or for others), forces users to hunt back for the original file.

Is there a particular technical hangup preventing the storing of manually uploaded files? I haven't looked into the backend of the project and I'm sure I wouldn't be much help, but I (and I'm sure others) would be happy to donate to have this feature added!

**Comment by itsheng** [comment]
Or can we just save the uploaded files into the SMB folder? Then the app can automatically pick up the new files?
