### ISSUE TITLE
Reg:S3 bucket Mount server upload data AWS console

### ISSUE THREAD

**Issue by itnoreplymax** [RD17/ambar#229]
HI,
My Ambar setup is working fine and I can search any document I submit with the portal. But, my {dataPath} still remains empty. I was expecting to find here Ambar data.. I tried local volume & S3 bucket but no luck to store my { data path}.

1) I have checked with  s3 bucket and create text file , It's indexed and viewed our Web UI Portal.After that i loged my s3 bucket  file was not present.

2) I have uploaded file in Aws S3 Bucket console and checked with Ambar Web UI it's not list out also the file not present in mounted path in server.

Kindly suggest with me.

**Comment by itnoreplymax** [comment]
HI,
  Is any updates

**Comment by itnoreplymax** [comment]
HI,
Is any updates

**Comment by itnoreplymax** [comment]
Dear Team,
    Kindly suggest with me. I can upload a file S3 bucket through AWS Console but the file not replicate/reflect in Our webUI. Also file not stored in s3 bucket mounted path in server...

**Comment by sochix** [comment]
@itnoreplymax sorry we're currently busy on our projects. Post your docker-compose here, I'll check it in a free time

**Comment by itnoreplymax** [comment]
@sochix Sorry for the delay reply. I went long holidays,so i can't see your message.  Please find the attachemnt and proceed. 

[docker compose file.txt](https://github.com/RD17/ambar/files/3133980/docker.compose.file.txt)
![s3 bucket terminal](https://user-images.githubusercontent.com/34542563/57009059-f90af700-6c11-11e9-8736-6a9072419863.png)
![fsatab entry](https://user-images.githubusercontent.com/34542563/57009060-f9a38d80-6c11-11e9-90ef-3ec4a0b78144.png)

**Comment by itnoreplymax** [comment]
Hi,
  Is any updates
