### ISSUE TITLE
Feature Request: On-line PDF Viewer

### ISSUE THREAD

**Issue by fictionalname** [RD17/ambar#23]
Hello,

Like other users here, I have tried other open source document management software but have found it overly complicated and bloated for my needs.  I'm most impressed with your product so far, but there is some functionality which I have seen elsewhere which I think would make your product even better.

It is great that you have made all of the text in the PDF searchable and I like that it shows the paragraph where the key word is found.  When I was testing it with some files, I though it would be very useful to be able to view the original PDF file on-line to see the original formatting and graphics without having to download the file and view it in a local viewer.  This would be especially useful when using your product on a tablet.

I guess you could include viewers for other file types if they are available, but I feel that a PDF viewer would be most useful.

Thanks for the excellent software - I can't wait to see what new features are added with the next update!

**Comment by sochix** [comment]
Added in [Release v0.9.2](https://github.com/RD17/ambar/blob/master/CHANGELOG.md#092-2017-04-27)
