### ISSUE TITLE
Getting crawl errors for ambar instance.

### ISSUE THREAD

**Issue by abpattnayakAptus** [RD17/ambar#238]
I was fiddling with custom tagging but i keep getting these errors in the crawling. I am also not seeing any changes in the logs for ambar pipeline. Maybe i am looking in the wrong place. Can someone please help me out ?

`
my-files_1    | { RequestError: Error: connect ECONNREFUSED 192.168.48.6:8080
my-files_1    |     at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
my-files_1    |     at Request.plumbing.callback (/node_modules/request-promise-core/lib/plumbing.js:87:29)
my-files_1    |     at Request.RP$callback [as _callback] (/node_modules/request-promise-core/lib/plumbing.js:46:31)
my-files_1    |     at self.callback (/node_modules/request/request.js:185:22)
my-files_1    |     at emitOne (events.js:116:13)
my-files_1    |     at Request.emit (events.js:211:7)
my-files_1    |     at Request.onRequestError (/node_modules/request/request.js:881:8)
my-files_1    |     at emitOne (events.js:116:13)
my-files_1    |     at ClientRequest.emit (events.js:211:7)
my-files_1    |     at Socket.socketErrorListener (_http_client.js:387:9)
my-files_1    |     at emitOne (events.js:116:13)
my-files_1    |     at Socket.emit (events.js:211:7)
my-files_1    |     at emitErrorNT (internal/streams/destroy.js:64:8)
my-files_1    |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
my-files_1    |     at process._tickCallback (internal/process/next_tick.js:180:9)
my-files_1    |   name: 'RequestError',
my-files_1    |   message: 'Error: connect ECONNREFUSED 192.168.48.6:8080',
` 

#162 I have gone through this issue and it is different than my case.

**Comment by SiddhantRoutray** [comment]
I also faced the same issues when I tried working on it.

**Comment by RaginiSharma17** [comment]
I tried doing the same but I'm not able to proceed with the desired log messages.

**Comment by smstern** [comment]
I faced the same issue and found a workaround. 

From my POV the crawler wants to connect to the wrong instance. The crawler should connect to the `webapi` instance instead of the configured (see src/config.js) `serviceapi`.

The workaround for now can be applied by adding the `links` block as shown here.

```
     image: ambar/ambar-local-crawler
     links:
       - webapi:serviceapi
     restart: always
```
