### ISSUE TITLE
Feature Request: Delete Document Button

### ISSUE THREAD

**Issue by fictionalname** [RD17/ambar#24]
Hi,

I hope you don't mind me giving another suggestion, but I think it is essential that there is a clean and easy way to delete files from the database within the GUI.  

I am planning to scan documents directly to the share that Ambar will import from, so there may be occasions where the document has not scanned correctly and I will have to rescan it.  This means I need to delete the old scan from the Ambar database to keep it tidy.  

A delete button on the search results screen next to each document would be sufficient so the incorrect document can be removed with a click.

Thanks again for all your hard work!

**Comment by sochix** [comment]
Hello, with removal feature we have an issue. Let's consider next scenario:

1. You add a crawler, with schedule to run every 5 minutes.
1. You remove some file 
1. The file appear again as crawler will add it

We're puzzled on how we can safely remove files from Ambar

**Comment by fictionalname** [comment]
Hi!

Thanks for your response.

I guess that in the scenario you have detailed, you would want the system to add the file back in as it currently exists in your within your list of live documents.  

I would say that in my original suggestion, the document would have been deleted from the location where the crawler is looking so it won't be added again.  This means that the document should be deleted from the Ambar database as well.  You could either set a delete option on the file in the GUI, or better still, have the choice to automatically delete files from the Ambar database which are no longer in the crawler location.

Do you think this sounds like a good idea?

Thanks!

**Comment by sochix** [comment]
Hi @fictionalname , thanks for your comments and feedback. Finally we found a way to remove files form Ambar. We'll add it to the release in the next few weeks

**Comment by sochix** [comment]
Done. Check 0.10.0 release
