### ISSUE TITLE
License vs. 'Yes, it is forever free for noncommercial use.'

### ISSUE THREAD

**Issue by Sicaine** [RD17/ambar#242]
Hi,

i was a little bit shocked when i read the ambar.cloud website and it was stated that commercial is $50/month.

I do not like to miss-use software so i checked your repository and the license again. I assume you changed your opinion about it as it was free before.

It is your choice to do that but i like to ask a few clarifying questions before i delete it from my machine:

- Your License doesn't reflect what you write on your page. So is it open source and free for commercial use? Because the "MIT License" suggests so
- For which version / commit did you switch to nonfree?

Tx,

Sigi

**Comment by d4rken** [comment]
> i was a little bit shocked when i read the ambar.cloud website and it was stated that commercial is $50/month.

Where does it say that? On the website I see `You can buy prebuilt images here for 50$. It's one time payment. This small fee helps us stay motivated and develop Ambar.` which sounds like fancy way to donate to the project.

Also the code here is `MIT` so it's basically DIY (free) or donate once and get a ready to use image.

Not sure where you are getting this from?

**Comment by sochix** [comment]
@d4rken @Sicaine we're trying different models of monetization. Ambar is a big project and it take a lot of time to maintain it. We're decided to sell prebuilt images as it is not breaking the MIT license and will give us some money and enthusiasm to maintain the project.

**Comment by Siegfriedk** [comment]
@d4rken it was written in the README.md
See update of sochix https://github.com/RD17/ambar/commit/523df9d741258c5619d026b78829e8bf238d6395#diff-04c6e90faac2675aa89e2176d2eec7d8

And the ambar.cloud also mentioned it.

I assume it just got resolved :)
