### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by aaa-bbb111222** [RD17/ambar#249]
I'm on Mint 19.1 on qemu.
I downloaded repo, when edited docker-compose.yml file for building as mentioned here: https://github.com/chazu/ambar
but I'm getting this error. So what should I do to fix it?
![image](https://user-images.githubusercontent.com/53825110/62543489-ae2efa00-b866-11e9-9fc0-d48fe42f3655.png)

**Comment by aaa-bbb111222** [comment]
I tried to comment lines "RUN yarn install" and "RUN yarn run build" in Dockerfile in ServiceApi, WebApi, LocalCrawler,FrontEnd and error has gone (but I don't think that it will work properly). But hew appeared: 
![image](https://user-images.githubusercontent.com/53825110/62699124-7ef3c680-b9e7-11e9-8ccc-97442c82e86c.png)
I commented "COPY dist /usr/share/nginx/html" in Dockerfile in FrontEnd. It make the building complete, but this error has appeared:
![image](https://user-images.githubusercontent.com/53825110/62700329-528d7980-b9ea-11e9-9509-b35887207921.png)
So what I'm doing wrong? (Yes, I know, commenting lines in Dockerfile isn't a good idea to make docker build program, but at least build was without errors)

**Comment by aaa-bbb111222** [comment]
After re-running docker-compose I've got this:
![image](https://user-images.githubusercontent.com/53825110/62706150-9935a080-b9f7-11e9-8c27-fbed636b06ed.png)
So commenting lines in Dockerfile is definitely is not a great idea.
May be problem caused by Mint itself? or Qemu?

**Comment by Yavari** [comment]
I had to run `sysctl -w vm.max_map_count=262144` mentioned at https://ambar.cloud/docs/installation/ in order to get it to work.

**Comment by aaa-bbb111222** [comment]
Error (something like cannot copy dist) may come in Ubuntu Desktop & Server, so I really cannot gues what is the problem.
