### ISSUE TITLE
Help with installing ambar on Ubuntu (says it cannot find docker-compose)

### ISSUE THREAD

**Issue by eliluong** [RD17/ambar#25]
So I installed a 64-bit version of Ubuntu server inside VMware with the default settings. The only thing I changed was to install a few additional things (Samba file server and OpenSSH server). Next I run `sudo apt-get update` and then follow the instructions to install Docker CE. Adding the repository seems to go well, and then I install docker, and I follow step 2 (`sudo apt-get install docker-ce`). I am able to run the hello-world container that outputs a successful message. `docker --version` gives me `v17.03.1-ce, build c6d412e`.

Next I try to install docker-compose. pip is not installed by default it seems, so I run `sudo apt install python-pip`. pip version is 8.1.1 (python 2.7) if that matters. Next I run `pip install docker-compose`. It completes and mentions a newer version of pip is available. I execute the wget command on the blog, followed by `sudo ./ambar.py install`. Here I run into an issue- docker-compose not found. But `docker-compose --version` returns version 1.12.0, build b31ff33.

Yesterday I had a different error (ERROR: In file 'docker-compose.yml' service 'version' doesn't have any configuration options), but today is different. I'm not proficient with linux and all its permissions and various directories, so if it's obvious something is wrong, I won't see it. Thanks for any help!

**Comment by isido993** [comment]
Hello!
Try this: `sudo chmod +x /usr/local/bin/docker-compose`
After, try `sudo ./ambar.py install` again.

**Comment by hartmch** [comment]
I had this same issue.  I ran 
`pip uninstall docker-compose`
then
`sudo pip install docker-compose`
and it fixed my issue.  Not sure if the command by fpd4444 would of worked also.

**Comment by eliluong** [comment]
Okay, I ended up having to do the `curl` command to pull the latest docker-compose and then put it in `/usr/bin/docker-compose` and `chmod +x` for that directory. Is that an incorrect way of doing it?

Now ambar installs and I can load the web ui. I'm able to upload some files and it does register that documents have been uploaded under the total MB uploaded. But nothing shows up in search or in statistics panel.

I'm not sure what logs to pull to give you additional information. I rebooted the VM and now it's just stuck on the loading screen with the loading icon ..

**Comment by isido993** [comment]
@eliluong 
Please try `sudo ./ambar.py restart`, wait a few minutes and post the output of `sudo docker logs ambar_webapi_1` here. Thnx

**Comment by sochix** [comment]
@eliluong does `restart` helps?

**Comment by sochix** [comment]
Closing as author did not reply :(
