### ISSUE TITLE
Required build steps for other components (not FrontEnd)

### ISSUE THREAD

**Issue by aaa-bbb111222** [RD17/ambar#256]
Instruction states required steps only for FrontEnd, but what about other components?

**Comment by ratio91** [comment]
just analogous:

e.g.
`cd Redis`
`docker build -t ambar/ambar-redis .`

etc.

**Comment by aaa-bbb111222** [comment]
@ratio91 
I mean last sentence:
>Note that some of the components require compilation or other build steps be performed on the host before the docker images can be built. For example, FrontEnd:
># Assuming a suitable version of node.js is installed (docker uses 8.10)
>$ npm install
>$ npm run compile

**Comment by ratio91** [comment]
I used a plain Ubuntu machine and was able to build all images without any issue.
Only for the frontend image, node was required.

**Comment by Yavari** [comment]
I am using this docker-compose file to run amber: https://gist.github.com/Yavari/276525fd22dd3812fa74b2478fc12c20

Change {ip} in the bottom of the file and language on line 79 from ambar_sv.

**Comment by aaa-bbb111222** [comment]
Thanks @ratio91 @Yavari 
Now it kinda works.
