### ISSUE TITLE
New language(s)?

### ISSUE THREAD

**Issue by bdevelops** [RD17/ambar#26]
Hello!
I was thinking about adding Polish language and support for users from Poland (separate documentation). I don't know if I can help with first thing, but I can definitely help with the second one.

Cheers.

**Comment by sochix** [comment]
Hello! 
> I was thinking about adding Polish language
You mean polish language analyzer and OCR?

> support for users from Poland (separate documentation)
As a start point you can translate README.md to Polish language.

Thanks for your contribution!

**Comment by bdevelops** [comment]
> You mean polish language analyzer and OCR?
Yes.

> As a start point you can translate README.md to Polish language
I'll start today! :)

**Comment by bdevelops** [comment]
Hello again!
Just finished translating readme, you can find it in my fork: https://github.com/bdevelops/ambar

**Comment by sochix** [comment]
@bdevelops nice job!

I've added link to polish version of Readme and also added you to the contributors list. 

Polish language analyzer will be added ASAP

**Comment by bdevelops** [comment]
Thank you! :)
