### ISSUE TITLE
DB Reset w/o reinstall

### ISSUE THREAD

**Issue by coolh** [RD17/ambar#265]
Hi, first, thanks for this great product, we are testing it and we didn't find any issues so far.
One thing that I want to know is if there is some way to reset the database without reinstalling the server.

Thanks for your help
F-

**Comment by isido993** [comment]
Hi, just stop Ambar, remove everything from db, es and rabbit folders, and start it again.

**Comment by coolh** [comment]
Hi, thanks for your response, I tried that at first, but after I restart the service, It shows an "oops" error and the search didn't work.

**Comment by isido993** [comment]
Are you sure that you removed everything and properly restarted Ambar? Did you stop it with 'docker-compose down'?
