### ISSUE TITLE
Getting lots of the following 2 errors running docker-compose build

### ISSUE THREAD

**Issue by AYapejian** [RD17/ambar#268]
Running latest off master I see lots of `index_not_found` errors.  At what point and whose responsibility is it to post the index to es?

```
serviceapi_1    | { Error: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="ambar_file_data" & index_uuid="_na_" & index="ambar_file_data" }
serviceapi_1    |     at respond (/node_modules/elasticsearch/src/lib/transport.js:289:15)
serviceapi_1    |     at checkRespForFailure (/node_modules/elasticsearch/src/lib/transport.js:248:7)
serviceapi_1    |     at HttpConnector.<anonymous> (/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
serviceapi_1    |     at IncomingMessage.wrapper (/node_modules/lodash/lodash.js:4929:19)
serviceapi_1    |     at emitNone (events.js:111:20)
serviceapi_1    |     at IncomingMessage.emit (events.js:208:7)
serviceapi_1    |     at endReadableNT (_stream_readable.js:1064:12)
serviceapi_1    |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
serviceapi_1    |     at process._tickCallback (internal/process/next_tick.js:180:9)
serviceapi_1    |   status: 404,
serviceapi_1    |   displayName: 'NotFound',
serviceapi_1    |   message: '[index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="ambar_file_data" & index_uuid="_na_" & index="ambar_file_data" }',
serviceapi_1    |   path: '/ambar_file_data/ambar_file/_search',
serviceapi_1    |   query: { _source: 'false' },
serviceapi_1    |   body:
serviceapi_1    |    { error:
serviceapi_1    |       { root_cause: [Array],
serviceapi_1    |         type: 'index_not_found_exception',
serviceapi_1    |         reason: 'no such index',
serviceapi_1    |         'resource.type': 'index_or_alias',
serviceapi_1    |         'resource.id': 'ambar_file_data',
serviceapi_1    |         index_uuid: '_na_',
serviceapi_1    |         index: 'ambar_file_data' },
serviceapi_1    |      status: 404 },
serviceapi_1    |   statusCode: 404,
serviceapi_1    |   response: '{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"ambar_file_data","index_uuid":"_na_","index":"ambar_file_data"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"ambar_file_data","index_uuid":"_na_","index":"ambar_file_data"},"status":404}',
serviceapi_1    |   toString: [Function],
serviceapi_1    |   toJSON: [Function] }
```

**Comment by AYapejian** [comment]
So I found that `[index_not_found_expcetion]` occurs when you don't have a valid `langAnalyzer` value set in the environment.  I mistakenly had `en` instead of `ambar_en` so that gets around the the index issue.  However now I've built on 2 different systems and everything launches just fine however there are http connection errors ( I don't have that exact message handy I'll have to get it if anyone ever responds to these issues )... at this point I'm not even sure the project is active and have spent quite a bit of time trying to get things running.  I'll wait for a response before I dig in further.

**Comment by loic49** [comment]
I've got the same problem after uploading my first document I have `[index_not_found_exception]` error, here it is :

`2019-10-21 20:37:07.862: [webapi] [error] [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="ambar_file_data" & index_uuid="_na_" & index="ambar_file_data" } Error: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="ambar_file_data" & index_uuid="_na_" & index="ambar_file_data" } at respond (/node_modules/elasticsearch/src/lib/transport.js:289:15) at checkRespForFailure (/node_modules/elasticsearch/src/lib/transport.js:248:7) at HttpConnector.<anonymous> (/node_modules/elasticsearch/src/lib/connectors/http.js:164:7) at IncomingMessage.wrapper (/node_modules/lodash/lodash.js:4929:19) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9)`

In my docker-compose, here my environments variables for serviceapi :
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=ambar_en  
      - SLAO_HOSTNAME=ambar 

Can't find what's wrong with my config. I send you 50$ for prebuild docker image (can't wait to receive my login so I build my own docker image from your source on github), hope you can help me.

Best regards

**Comment by loic49** [comment]
36 hours after my payment (50$) I didn't receive anything, no response for my last question, project is dead ?

**Comment by sochix** [comment]
Hello, please send your email address to hello@ambar.cloud. Email that
linked to your PayPal account is not working.

ср, 23 окт. 2019 г. в 08:26, loic49 <notifications@github.com>:

**Comment by loic49** [comment]
I send you a message on your email (hello@ambar.cloud) 13 hours ago, but no response, is it normal ?

**Comment by sochix** [comment]
@isido993 can't send you a message. Got following error:

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  loic.a***********@cegetel.****
    host smtp-in.sfr.fr [93.17.128.123]
    SMTP error from remote mail server after end of data:
    550 5.7.1 SPF permanent error:
Reporting-MTA: dns; in02.relay.hosting.nic.ru

Action: failed
Final-Recipient: rfc822;loic.*****@cegetel.***
Status: 5.0.0
Remote-MTA: dns; smtp-in.sfr.fr
Diagnostic-Code: smtp; 550 5.7.1 SPF permanent error:

**Comment by sochix** [comment]
@loic49 maybe you can provide another email address?

**Comment by loic49** [comment]
New message send with loic.a*******@la****.in****, do you received ?

**Comment by sochix** [comment]
@loic49 received!

**Comment by AYapejian** [comment]
So is there only support for those who pay for an image vs. those of us that build our own?  Why not just discuss the problem in the issue thread?

**Comment by pedropombeiro** [comment]
It's quite obvious that the project owner has no interest in people building and running the open source version of the project. That's a red flag in terms of future maintanability of this project, so I guess it's time to look for an alternative in https://github.com/awesome-selfhosted/awesome-selfhosted#search-engines

**Comment by allsolovey** [comment]
How to solve this problem?
