### ISSUE TITLE
search for chinese language

### ISSUE THREAD

**Issue by hellomanjack** [RD17/ambar#27]
Can you add search support for chinese language file ? Thanks!

**Comment by sochix** [comment]
Hello @hellomanjack!
Does CJK lang analyzer work for you?

**Comment by hellomanjack** [comment]
@sochix I think IKAnalyze is better in supporting chinese.  Thanks!

**Comment by isido993** [comment]
I couldn't make IKAnalyze working... ES says the structure of the archive is incorrect, I can rebuild it manually but it's not the best way to add modules into production.

Maybe [this analyzer](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-smartcn.html) would suit your needs?

**Comment by hellomanjack** [comment]
Yeal，thanks

**Comment by isido993** [comment]
Ok! We'll add it into the next release.

**Comment by sochix** [comment]
Added in 0.9.5 release
