### ISSUE TITLE
Docker build failure under Ubuntu 18.04

### ISSUE THREAD

**Issue by mr-david** [RD17/ambar#272]
Attempting to build from scratch gives the following error:

$ docker build . -t ambar
Sending build context to Docker daemon  1.954MB
Step 1/8 : FROM nginx:latest
 ---> 231d40e811cd
Step 2/8 : RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl
 ---> Using cache
 ---> 27f94c85400d
Step 3/8 : ENV TZ=UTC
 ---> Using cache
 ---> cecbbaec99c2
Step 4/8 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Using cache
 ---> f343be593a34
Step 5/8 : COPY default /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> 01fb4d6b1aee
Step 6/8 : COPY dist /usr/share/nginx/html
COPY failed: stat /var/lib/docker/tmp/docker-builder696796482/dist: no such file or directory
dcolon@plexy:~/source/ambar/FrontEnd$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Comment by olislaeda** [comment]
cd ~/source/ambar/FrontEnd/
npm install
npm run compile

PROFIT :-)
