### ISSUE TITLE
docker-compose file for building

### ISSUE THREAD

**Issue by maltokyo** [RD17/ambar#281]
This repository should include a docker-compose file for building from scratch.  Does anyone have one to share?  Thanks!

**Comment by bennywa9** [comment]
Here is a link to the docker-compose file I used to build locally. It builds for me and the stack boots, but I'm not able to access the frontend in my web browser. If you get it working let me know. [https://github.com/bennywa9/ambar_build](https://github.com/bennywa9/ambar_build)

**Comment by maltokyo** [comment]
Thanks! Will give it a try!

**Comment by ark-** [comment]
> Here is a link to the docker-compose file I used to build locally. It builds for me and the stack boots, but I'm not able to access the frontend in my web browser. If you get it working let me know. https://github.com/bennywa9/ambar_build

Yep, frontend isn't loading for me too. One issue I found with your `docker-compose.yml` is that  in frontend your ports should be

```
    ports:
      - "82:80"
```

As the container port is 80, but I assume you want to expose 82.
