### ISSUE TITLE
Error building FrontEnd

### ISSUE THREAD

**Issue by AshleyOboe** [RD17/ambar#286]
I'm getting a build error on frontend

$ cd frontend
$ docker build . -t frontend

Error:
`Sending build context to Docker daemon  177.4MB
Step 1/8 : FROM nginx:latest
 ---> 8cf1bfb43ff5
Step 2/8 : RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl
 ---> Using cache
 ---> f1829a617007
Step 3/8 : ENV TZ=UTC
 ---> Using cache
 ---> ca4475816da7
Step 4/8 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Using cache
 ---> 0dbd9ed2f2d1
Step 5/8 : COPY default /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> 442b575b0027
Step 6/8 : COPY dist /usr/share/nginx/html
COPY failed: stat /var/lib/docker/tmp/docker-builder302332317/dist: no such file or directory`

Running Docker version 19.03.8, build afacb8b 

I was using a newer version and rolled back to this current stable version of Docker.

Thanks.

**Comment by iddqd-dev** [comment]
U must use "npm install" and "npm run compile" in frontend folder before u run docker build

**Comment by iddqd-dev** [comment]
And dont forget use tweaks 4 correctly working
sudo su
echo "vm.max_map_count=262144" >> /etc/sysctl.conf
echo "net.ipv4.ip_local_port_range="15000 61000"" >> /etc/sysctl.conf
echo "net.ipv4.tcp_fin_timeout=30" >> /etc/sysctl.conf
echo "net.core.somaxconn=1024" >> /etc/sysctl.conf
echo "net.core.netdev_max_backlog=2000" >> /etc/sysctl.conf
echo "net.ipv4.tcp_max_syn_backlog=2048" >> /etc/sysctl.conf
echo "vm.overcommit_memory=1" >> /etc/sysctl.conf
reboot

**Comment by iddqd-dev** [comment]
im helped u?
