### ISSUE TITLE
How to check data in elasticsearch using ambar?

### ISSUE THREAD

**Issue by N-CP** [RD17/ambar#29]
what is the name of index is created after uploading a pdf file on ambar???
also the text file which I got in that file image text is not present which is my main aim.

**Comment by sochix** [comment]
The name of ES index is unique for each user, I recommend you to use `GET /_cat/indices/` on Ambar ES to understand how Ambar works internally

**Comment by N-CP** [comment]
How I can Start ambar ES??
And where i will get that ES in ambar???

**Comment by N-CP** [comment]
Ambar is stopped working.
Giving error 502 Bad gateway
please reply

**Comment by N-CP** [comment]
please help me to resolve the error.
Ambar is stopped working.Shows 502 Bad Gateway error

**Comment by sochix** [comment]
@N-CP the thread miss it subject, please create a new one with concrete problem and it's full description

**Comment by N-CP** [comment]
Hello
Ilya Pirozhenko
I created a new issue for ambar.Following is the link
https://github.com/RD17/ambar/issues/31

please look into that.

Thanks & Regards
N-CP

**Comment by sochix** [comment]
@N-CP got it! Thanks!

**Comment by N-CP** [comment]
if u want browser console then I can also paste here.Can I??

**Comment by N-CP** [comment]
/favicon.ico Failed to load resource: the server responded with a status of
502 (Bad Gateway)
192.168.15.137/ Failed to load resource: the server responded with a status
of 502 (Bad Gateway)

this is my console log
