### ISSUE TITLE
Frontend compile error related to node-saas 

### ISSUE THREAD

**Issue by gyillikci** [RD17/ambar#290]
Hi,

When ran npm install I got node-saas related error o I changed the version of it 4.12.0 in the package.json.
Other than that, npm run compile throws the error below. 

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ambar-frontend@2.1.19 compile: `better-npm-run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ambar-frontend@2.1.19 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-09-15T12_56_15_749Z-debug.log
`

how can I tackle this issue.

Thanks

**Comment by kevung** [comment]
I encounter the same problem as @gyillikci

**Comment by iddqd-dev** [comment]
> Hi,
> 
> When ran npm install I got node-saas related error o I changed the version of it 4.12.0 in the package.json.
> Other than that, npm run compile throws the error below.
> 
> `npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! ambar-frontend@2.1.19 compile: `better-npm-run compile`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ambar-frontend@2.1.19 compile script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/user/.npm/_logs/2020-09-15T12_56_15_749Z-debug.log
> `
> 
> how can I tackle this issue.
> 
> Thanks

Lmao. And where is the content of  /home/user/.npm/_logs/2020-09-15T12_56_15_749Z-debug.log
