### ISSUE TITLE
 => ERROR [5/5] COPY dist /usr/share/nginx/html 

### ISSUE THREAD

**Issue by maspiter** [RD17/ambar#292]
FrontEnd dockerfile tries to copy file that does not exist

**Comment by iddqd-dev** [comment]
Hi. U must run from ambar folder
cd ambar/FrontEnd/
npm install
npm run compile

**Comment by maspiter** [comment]
OK thanks for the reply, got it.

**Comment by iddqd-dev** [comment]
ur welcome
