### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by aandis** [RD17/ambar#293]
If I upload a document, I get an error. Same when I try to search. Here's a console screenshot

![Screenshot from 2020-11-06 15-32-20](https://user-images.githubusercontent.com/4983347/98353471-540e7d00-2045-11eb-9346-2eaee7b361c0.png)

**Comment by fivestones** [comment]
I just get a timeout when I go to the demo right now.

**Comment by aandis** [comment]
looks like its back up. Closing.
