### ISSUE TITLE
Optional "Disable OCR"-Flag for Crawler

### ISSUE THREAD

**Issue by cmprmsd** [RD17/ambar#296]
Is there the possibility to tell the crawler not to do OCR?
E.g. if there are many documents where I know it's just machine readable pdfs.

**Comment by cmprmsd** [comment]
Thanks.

**Comment by iddqd-dev** [comment]
> Is there the possibility to tell the crawler not to do OCR?
> E.g. if there are many documents where I know it's just machine readable pdfs.

ocrPdfMaxPageCount=0

**Comment by cmprmsd** [comment]
Nice! Where can this option be configured?

**Comment by iddqd-dev** [comment]
> Nice! Where can this option be configured?
In docker-compose.yml
 environment:
     - ocrPdfMaxPageCount=0
