### ISSUE TITLE
Ambar is not extracting image text from pdf

### ISSUE THREAD

**Issue by N-CP** [RD17/ambar#30]
I upload pdf in ambar but not geting the image text extracted in output .txt file
[CLASS-1-6.pdf](https://github.com/RD17/ambar/files/976358/CLASS-1-6.pdf)

**Comment by sochix** [comment]
Hello! I explored a bit your sample file and found that it's a pdf with scanned images inside. It's have more than thousand pages. It depends on configuration of your machine, but on average it will take more than 8 hours to OCR 1000 pages. I recommend you to wait until Ambar process your file completely.

**Comment by N-CP** [comment]
Ok.Thanks

**Comment by N-CP** [comment]
I started ambar but is not loading on web???
I got error 502 bad gateway

**Comment by sochix** [comment]
please create a new issue for this error
