### ISSUE TITLE
How to use ambar-ES for document search

### ISSUE THREAD

**Issue by N-CP** [RD17/ambar#31]
Hello,
I installed ambar in my machine.But when I start it, sometime UI not get loading.Giving 502 Bad gate way error.
& When It start I am not able to understand where to write search query for ES indices.How to check whether document is present in ES or not..

**Comment by N-CP** [comment]
Hi
not able to parse image text in ambar.what is the solution?
If OCR is automatically fetch that data then I m not getting proper result.

**Comment by sochix** [comment]
Hello @N-CP , finally we have kind-of-solution for you! Check our side project for extracting text from any file [RawText](https://rawtext.ambar.cloud/). I hope it will suits your needs.

**Comment by N-CP** [comment]
Hi,
Thanks Ilya.I will check it and let you know.

Thanks & Regards,
Nikhil Parab

**Comment by N-CP** [comment]
Hi @Ilya,
I have getting some error while installation of rawtext. Connection refuse
error I got. Can yanks & Rou please help me solve it out???


Thanks & Regards,
nikhil Parab

**Comment by N-CP** [comment]
Hi @Ilya,

I have getting some error while installation of rawtext.(Connection refused
error). Could you please help me to solve it out???


Thanks & Regards,
Nikhil Parab

**Comment by sochix** [comment]
@N-CP rawText is not ready yet, now we are collecting emails. You'll get the mailing newsletter when we release it.
