### ISSUE TITLE
Feature request: RSS feed crawler

### ISSUE THREAD

**Issue by jenkin** [RD17/ambar#33]
When items contain [enclosures](http://cyber.harvard.edu/rss/rss.html#ltenclosuregtSubelementOfLtitemgt) linking to available documents.

**Comment by sochix** [comment]
Hi @jenkin . Can you please describe this crawler a bit? Should it fetch all linked documents? And if the document an html page should it fetch it too?

**Comment by jenkin** [comment]
RSS specifications require the mime type as attribute of [enclosure tag](http://cyber.harvard.edu/rss/rss.html#ltenclosuregtSubelementOfLtitemgt): "It has three required attributes: url says where the enclosure is located, length says how big it is in bytes, and type says what its type is, a standard MIME type." So the crawler should fetch only enclosures with a supported (by Ambar) mime type (ie. application/pdf). Other types, such as mp3 in podcast feeds, will be ignored.

**Comment by sochix** [comment]
@jenkin got it! Can you please also describe use case for the RSS crawler? What kind of data you want to crawl with it? Newsletters or what?

**Comment by sochix** [comment]
[Check our support options](https://github.com/RD17/ambar#support)
