### ISSUE TITLE
Feature request: Hancom Office file(.hwp) support

### ISSUE THREAD

**Issue by kulaw327** [RD17/ambar#34]
Hancom Office or (aka Hangul Word Processor) file (.hwp) is a de facto standard in Korea.
It is widely used by the government and courts, so it is a must-have option in Korea. 
But Dtsearch and Windows search does not support it. Ifilters are commercially available at a high price. 
Hwp support would make Ambar very competitive in Korea. 

Hwp format was adopted as a standard and its specification was made public but only in Korean. 
https://www.hancom.com/board/noticeView.do?artcl_seq=6453

But there are some hwp parsing project you might want to reference. 
https://sites.google.com/site/h2tlib/
https://github.com/ddoleye/java-hwp

**Comment by sochix** [comment]
Got it. Can you please help us with library documentation translation from korean?

**Comment by sochix** [comment]
@kulaw327 we've added it, wait for the next release to try it

**Comment by sochix** [comment]
@kulaw327 sad to say, but we have a problems integrating hwp into our pipeline. We need more time.

**Comment by sochix** [comment]
[Check our support options](https://github.com/RD17/ambar#support)
