### ISSUE TITLE
Feature request: S3 crawler

### ISSUE THREAD

**Issue by jamesinc** [RD17/ambar#35]
I'd really like to be able to crawl an S3 bucket. I feel sketchy serving web traffic out of my Dropbox!

**Comment by sochix** [comment]
Hi! FTP or SMB crawler will not work for you?

**Comment by jamesinc** [comment]
It would be possible to work around it using [s3fs](https://github.com/s3fs-fuse/s3fs-fuse). I was just hoping for a native solution that didn't require mounting a bucket into a directory. It would work, but it is not ideal, as it would want to cache the contents of the bucket to the local disk. In this case, I'm trying to avoid needing lots of storage on the instance running Ambar.

**Comment by jmgilman** [comment]
+1

**Comment by sochix** [comment]
In the latest release you can mount S3 folder to local crawler

**Comment by AyKarsi** [comment]
how can I mount a s3 folder to the local crawler?

**Comment by sochix** [comment]
@AyKarsi just google on how to map s3 folder to local folder, and then map this local folder to the crawler.
