### ISSUE TITLE
'utf-16-le' codec error

### ISSUE THREAD

**Issue by rickythefox** [RD17/ambar#36]
Hi!

I'm getting the following error for some of my files when crawling them using the SMB crawler. The same file can be uploaded manually and works ok.

`[error] 'utf-16-le' codec can't decode bytes in position 18-19: illegal encoding.` 

What to do?

**Comment by isido993** [comment]
@rickythefox 

We've never had such issue with our and our customers' files.
Please send us one of these files and we'll look into the problem.

Thnx.

**Comment by rickythefox** [comment]
Will try to find an example file for you, the ones are use are quite sensitive so I probably can't share them.

**Comment by sochix** [comment]
@rickythefox any news?
