### ISSUE TITLE
Feature Request: Provide Email Preview or let users customize the preview

### ISSUE THREAD

**Issue by gewuerzgurke84** [RD17/ambar#40]
Hi there,

I was really happy to find this project after spending quite some time for Solr, Datafari, manifoldcf, etc. PoCs. Finally something that works out of the box and allows me to crawl my local documents (using smb) and my emails.

I think it would be really helpful to have a preview functionality for .eml-Files as well. As I'm not sure if there are any suitable JS library to achieve that another helpful improvement could be to let the ambar admin customize the preview url. The approach to let google document viewer preview everything helps to get things up quickly, but fails if you want to show previews/documents using another software.

Cheers,
 Alex

**Comment by sochix** [comment]
I like this idea, will include it to our internal roadmap

**Comment by sochix** [comment]
Hello @gewuerzgurke84 , in 1.2.0 release we've added text preview to every document, check it out.
