### ISSUE TITLE
Install issue on proxmox lxc

### ISSUE THREAD

**Issue by tscibilia** [RD17/ambar#42]
The install process was easy and straightforward. I was excited to get started with ambar, but at the very end I received a message in the console 

`sysctl: cannot stat /proc/sys/net/ipv4/tcp_fin_timeout: No such file or directory`

I know lxc containers have an issue running docker (which I was able to get around by modifying the lxc conf file to include some [extra parameters](http://ashish1099.github.io/blog/2015/05/23/docker-inside-lxc/). I realize this is probably not the safest practice but the container would only be accessible on a local network. Since I'm still having issues with the container I was hoping to see if anyone had a solution I missed.

**Comment by sochix** [comment]
Hello @tscibilia ! This line `sysctl -w net.ipv4.tcp_fin_timeout=30 ` was added to tune Ubuntu tcp/ip stack, I think in your case just comment it out in your `ambar.py` file:
```
# runShellCommandStrict('sysctl -w net.ipv4.tcp_fin_timeout=30')
```

**Comment by tscibilia** [comment]
thanks that worked, except i had to comment out a few other errors.

`# runShellCommandStrict('sysctl -w net.ipv4.tcp_fin_timeout=30')`

`# runShellCommandStrict('sysctl -w net.core.netdev_max_backlog=2000')`
`# runShellCommandStrict('sysctl -w net.ipv4.tcp_max_syn_backlog=2048')`

**Comment by sochix** [comment]
Nice!
