### ISSUE TITLE
Feature Request: Support for easy installation on Cloudron

### ISSUE THREAD

**Issue by pavanagrawal123** [RD17/ambar#44]
Cloudron is a popular way to selfhost services easily. Support for cloudron would be awesome!

**Comment by sochix** [comment]
I have a chat with cloudron support and they said:

> cloudron doesn't have rabbitmq, elasticsearch yet but for the moment you can include it in your docker image

As I understand cloudron can host only single docker image per application, which isn't the case for Ambar as it's distributed as a set of Docker images.

So as for now, we can't support cloudron
