### ISSUE TITLE
Ambar wont Autostart

### ISSUE THREAD

**Issue by davemanster** [RD17/ambar#46]
Hello

When restarting Ubuntu this is the output of docker ps

> CONTAINER ID        IMAGE                         COMMAND                  CREAT                                                                    ED             STATUS                              PORTS                                                                                                  NAMES
5ec43d188c10        ambar/ambar-pipeline:latest   "/bin/sh -c 'pytho..."   37 mi                                                                    nutes ago      Restarting (139) 49 seconds ago                                                                                                            ambar_pipeline_p0
2ed6b189aebd        ambar/ambar-crawler:latest    "/bin/sh -c 'pytho..."   37 mi                                                                    nutes ago      Restarting (1) 36 seconds ago                                                                                                              ambar_crawler_c0
baac19554af4        ambar/ambar-frontend:latest   "/bin/sh -c 'echo ..."   38 mi                                                                    nutes ago      Up 3 minutes                        80/tcp                                                                                                 ambar_frontend_1
d1ef1edac298        ambar/ambar-webapi:latest     "/bin/sh -c 'docke..."   38 mi                                                                    nutes ago      Restarting (1) 28 seconds ago                                                                                                              ambar_webapi_1
53931fb03307        ambar/ambar-proxy:latest      "/entrypoint.sh"         38 mi                                                                    nutes ago      Up 3 minutes                        0.0.0.0:889-890->889-890/tcp                                                                           ambar_proxy_1
0cd5938e8bfa        ambar/ambar-es:latest         "/docker-entrypoin..."   38 mi                                                                    nutes ago      Up 3 minutes                        0.0.0.0:9200->9200/tcp, 9300/                                                                    tcp   ambar_es_1
99ecced7bd96        redis:alpine                  "docker-entrypoint..."   38 mi                                                                    nutes ago      Up 3 minutes                        0.0.0.0:6379->6379/tcp                                                                                 ambar_webapi-cache_1
7971cf6807cd        ambar/ambar-mongodb:latest    "/entrypoint.sh"         38 mi                                                                    nutes ago      Restarting (2) About a minute ago    

Pipeline, crawler, and webapi are in an endless restart loop.

If I manually run ./ambar.py start then they work fine and come up as expected.

I would like this to autostart though. 

Bug?

**Comment by isido993** [comment]
Hi,

Just add `python3 /**THE FOLDER WITH AMBAR MANAGEMENT SCRIPT**/ambar.py restart` to your `/etc/rc.local` file.

**Comment by davemanster** [comment]
Any way you can add step by step ?

**Comment by sochix** [comment]
@davemanster onboarding and installation session via skype included in Ambar Enterprise Edition
