### ISSUE TITLE
Missing trailing slash on proxy_pass to frontend  

### ISSUE THREAD

**Issue by thangngoc89** [RD17/ambar#48]
Your original nginx config produced by default installation process.

```
server {
  listen 80;
  server_name ambar-fe;
  client_max_body_size 1024m;
  location /api/ {
    proxy_pass http://webapi:8080/api/;
  }
  location / {
    proxy_pass http://frontend:80;
  }
}
```

The last directive should be `proxy_pass http://frontend:80/;`

**Comment by luxflux** [comment]
This has been fixed with RD17/ambar-proxy@328084c9d124f2d51e8030bd994167ab8b5d742a, could you build a new docker image?

**Comment by thangngoc89** [comment]
@luxflux Do you guys have some kind of chat? I can't get ambar running on my machine at all. Upload function isn't working

**Comment by sochix** [comment]
@luxflux will update images ASAP

**Comment by sochix** [comment]
@thangngoc89 please, create a new issue with description of your problem

**Comment by sochix** [comment]
@luxflux @thangngoc89 images updated
