### ISSUE TITLE
Make IMAP crawler leave email unread

### ISSUE THREAD

**Issue by akropp** [RD17/ambar#52]
IMAP crawler should not mark emails as read.  At least in gmail, this is the current behavior.

If the fetch call in imapcrawler.py is changed to:
            callResult, data = self.connection.uid('fetch', messageId, '(BODY.PEEK[])')

This has the desired behavior on gmail.  I do not have other IMAP accounts to test.

**Comment by sochix** [comment]
Thanks for the feedback, will check it

**Comment by buster39** [comment]
Hi @akropp my gmail setup does not work. But yours seems to. Could you please post your crawler config for gmail? The part "Locations" and "credentials" are interesting for me.

Thanks

**Comment by sochix** [comment]
Done. @buster39 please create new issue with description of your problem
