### ISSUE TITLE
Cannot start mongodb using latest docker image

### ISSUE THREAD

**Issue by gridcellcoder** [RD17/ambar#55]
When using 

`https://blog.ambar.cloud/ambar-installation-step-by-step-guide-2/`

the app fails to starts dues to a mongodb error. I also ran `docker pull ambar/ambar-mongodb`

and attaching to that mongo-db container:

```
Error parsing YAML config: duplicate key: storage.wiredTiger.engineConfig.cacheSizeGB(canonical key: storage.wiredTiger.engineConfig.cacheSizeGB)
try 'mongod --help' for more information
```

**Comment by gridcellcoder** [comment]
And using the latest from git works better but in chrome console:

`Failed to start. Error: TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from http://:80
/api/`

**Comment by sochix** [comment]
> http://:80 /api/

@gridcellcoder you have empty ipaddress in `config.json` fix it and restart Ambar `sudo ./ambar.py restart`

**Comment by sochix** [comment]
@gridcellcoder does this help?

**Comment by gridcellcoder** [comment]
That helps thanks.
