### ISSUE TITLE
Bug/Feature: Filter by Month

### ISSUE THREAD

**Issue by thebetterjort** [RD17/ambar#56]
I don't know if this is a bug or by design.

I believe the current search should search 1 month from the day, and not categorically just the month itself.

eg) Today I search for a document that I did last month. July 7th, 2017. It doesn't show up in the search because it will only search for documents created in August.

**Comment by sochix** [comment]
Query `when:thismonth` - return results for current calendar month.  And you want to receive results for last 30 days, this type of query is not supported as for now. But we have it in plans
