### ISSUE TITLE
API methods to check processing status

### ISSUE THREAD

**Issue by jenkin** [RD17/ambar#62]
Sending file to ambar is an asynchronous task, so you have to poll API with the file id to check if processing is finished and to retrieve parsed text. But I find the endpoint response is "404 file not found" both for in processing files and failed ones.

Can you add a persistent status endpoint with similar information I can see in rabbit log?

**Comment by sochix** [comment]
@jenkin thank you for your feedback! We'll add this to our internal roadmap

**Comment by jenkin** [comment]
Thank you very much, for now I'll use a cache to keep track of processing files and set a time interval to check failed ones.
