### ISSUE TITLE
Number of hits before searching..Feature Will be awesome..

### ISSUE THREAD

**Issue by prog20901** [RD17/ambar#63]
If number of hits displayed before searching..It would be great...

Even google doesn't have the number of hits....

But number of hits are done and possible

ex: http://table.branham.org/#/main

Type any word and wait for 2 second it will show the number of hits possible for the given word or sentence.

**Comment by sochix** [comment]
Hello @jkathir , when this feature will be useful? We already have number of results in response it simply not displayed in UI

**Comment by prog20901** [comment]
we might type a single word or multiple words based on the number of hits shown. For example, when we say buyer assume it shows  1 lakh hits..we will add buyer protection...assume it shows 10,000 hits...we will add buyer user protection ...assume it shows 5,000 hits, we will add buyer user protection offer...this will be really great when we don't like to change the screen or search the hits and making the changing in the same page and same cursor itself...

**Comment by sochix** [comment]
@jkathir we will not add it to Ambar UI. You can use our REST API to display some information based on results count. 

Check the [search method](https://github.com/RD17/ambar/blob/master/API_DOC.md#search-for-documents-by-query). The count of results will be in `total` field.

**Comment by prog20901** [comment]
That will slow down the response of type-ahead as it depends upon network latency.
