### ISSUE TITLE
I don't use docker. Can you provide a generic scripted install?

### ISSUE THREAD

**Issue by partoneoftwo** [RD17/ambar#65]
I use Ubuntu containers with LXC/LXD. I cannot use Docker because my hypervisor does not support it. 

Installing Docker on my hypervisor will mess everything up. Can you make a generic install script so that I can get Ambar running in an lxc container?

Something like what Sandstorm.io has. 

Should work on Ubuntu 1604. Okithxbye

Can't wait to try the solution out :)

**Comment by sochix** [comment]
Hello @thomasfrivold! Sorry, but you can't install Ambar without Docker and also we can't create a *generic install script*. It's will not work by design.
