### ISSUE TITLE
Chrome shows blank page - Safari works

### ISSUE THREAD

**Issue by lucajung** [RD17/ambar#67]
Hi,
The Ambar Web UI works fine in Safari, but in Chrome it shows only a blank page with the Chat on the bottom right. The page title is: "Ambar is loading...".

**Chrome Console output:**
```
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH vendor.eef98c3c54a751d6bf8f.js
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH app.5800ae896ed146f4e02a.js
```

Thank you very much for your efforts!

**Comment by sochix** [comment]
Can not reproduce. Closing.
