### ISSUE TITLE
Can't load file > 100MB

### ISSUE THREAD

**Issue by rshibanov** [RD17/ambar#7]
When I try to download a large file, nothing happens. Upload button inactive.

**Comment by sochix** [comment]
Hello @rshibanov!
> When I try to download a large file

Maybe "upload"?

We have a 30 Mb limit on upload through UI, for perfomance reasons. To upload large files use SMB crawler. Tutorial: [Crawling Your Own Shared Folders](https://blog.ambar.cloud/advanced-ambar-usage-crawling-your-own-shared-folders/)

**Comment by rshibanov** [comment]
Thanks
