### ISSUE TITLE
Issue starting the docker with ambar_proxy

### ISSUE THREAD

**Issue by Pierrelemoine** [RD17/ambar#70]
Hi,
I have started to test Ambar online and I am very impressed. 
I installed it on my ubuntu but when I start the docker it displays error. 
Do you have idea where it's coming from please?

    Starting ambar_proxy_1 ... error
    
    ERROR: for ambar_proxy_1  Cannot start service proxy: b'driver failed programming external connectivity on endpoint ambar_proxy_1 (8b56dc0157cc34f86782eda38a49698951b1a69047c09e945d430b08077e07e8): Error starting userland proxy: lisStarting ambar_db_1 ... error
    
    ERROR: for ambar_db_1  Cannot start service db: b'driver failed programming external connectivity on endpoint ambar_db_1 (26a3fd57d94cc4cf3184db8652195524ef8342557f4495d73cf6cb678d5e11c2): Error starting userland proxy: listen tcp 0Starting ambar_rabbit_1 ... done
    
    ERROR: for proxy  Cannot start service proxy: b'driver failed programming external connectivity on endpoint ambar_proxy_1 (8b56dc0157cc34f86782eda38a49698951b1a69047c09e945d430b08077e07e8): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use'
    
    ERROR: for db  Cannot start service db: b'driver failed programming external connectivity on endpoint ambar_db_1 (26a3fd57d94cc4cf3184db8652195524ef8342557f4495d73cf6cb678d5e11c2): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use'
    ERROR: Encountered errors while bringing up the project.
    Traceback (most recent call last):
      File "./ambar.py", line 249, in <module>
    start(configuration)
      File "./ambar.py", line 191, in start
    runShellCommandStrict('docker-compose -f {0}/docker-compose.yml -p ambar up -d'.format(PATH))
      File "./ambar.py", line 47, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'docker-compose -f /root/docker-compose.yml -p ambar up -d' returned non-zero exit status 1

Thanks.

**Comment by sochix** [comment]
What OS you are using?

**Comment by Pierrelemoine** [comment]
Hi,
I am using Ubuntu. I have restarted with a fresh installation and now ambar starts. So it's fixed.
After that, I had another issue when I was accessing the server but it has been fixed by increasing the ram size of my VM to 2GB.

It works fine now.
