### ISSUE TITLE
Several questions about Ambar EE 

### ISSUE THREAD

**Issue by Pierrelemoine** [RD17/ambar#71]
Hi,
I have some questions about Ambar which is a really great tool by the way:
* Is it possible to install Ambar EE locally?
* If I install Ambar CE locally and would like to move to Ambar EE, is it possible to transfer data from one to another?
* What is the best way to update Ambar?
* Is that possible to search for multiple tags at the same time? For instance, try to find file with tags:ocr and tags:image?
* Does Ambar EE includes all updates at no additional cost? Do I pay it once or there is a kind of subscription somewhere?

thanks

**Comment by sochix** [comment]
Hello @Pierrelemoine !

> Is it possible to install Ambar EE locally?

Yep, but only after payment

> If I install Ambar CE locally and would like to move to Ambar EE, is it possible to transfer data from one to another?

Yep, it's possible

> What is the best way to update Ambar?

sudo ./ambar.py update

> Is that possible to search for multiple tags at the same time? For instance, try to find file with tags:ocr and tags:image?

Yep, use tags:image,ocr

> Does Ambar EE includes all updates at no additional cost? Do I pay it once or there is a kind of subscription somewhere?

You'll receive all updates. It's one time payment as for now, maybe in future we will change it to subscription, but only for new customers.
