### ISSUE TITLE
Feature Request: Favourite button and tagging multiple files

### ISSUE THREAD

**Issue by vo1cano** [RD17/ambar#73]
Hi, guys! You've made a really GREAT product! I think it would be useful not only for me to have two new features:
1. Sort of Favourite button in a document card (for example, near Hide) and item in the menu to show all documents marked as Favourite (like Hidden). Now I have to add 'like' tag and its not very convenient.
2. Add tags to all the documents loaded through the Dropzone at once.

**Comment by sochix** [comment]
Hi @vo1cano !

> Sort of Favourite button in a document card (for example, near Hide) and item in the menu to show all documents marked as Favourite (like Hidden). Now I have to add 'like' tag and its not very convenient.

We've made a new release Ambar 1.1.0. In this release we're added tags to sidebar, so i think it will solve problem 1.

> Add tags to all the documents loaded through the Dropzone at once.

Yep, it's planned to be done in the next release

**Comment by vo1cano** [comment]
Thanks a lot! Looking forward to the next release!

**Comment by sochix** [comment]
@vo1cano it's can be done as paid feature only, sorry
