### ISSUE TITLE
certain PDF files are not showing up in any search, even though the SMB crawl log says they were picked up

### ISSUE THREAD

**Issue by matt-taylor-tech** [RD17/ambar#74]
2017-09-07 17:25:01.231: [verbose] content found //outlook/invoices/combined_80669x170906180735.pdf
2017-09-07 17:25:01.288: [verbose] meta added //outlook/invoices/combined_80669x170906180735.pdf
2017-09-07 17:25:01.377: [verbose] content found //outlook/invoices/combined_80669x170906180739.pdf
2017-09-07 17:25:01.407: [verbose] meta added //outlook/invoices/combined_80669x170906180739.pdf

I cannot find either of these two by searching by filename, or date

**Comment by sochix** [comment]
Hi @thesuigeneris ! Ambar workflow for new files includes two steps:
1. Crawl file with crawler, SMB crawler in your case
2. Process file with the pipeline

Processing can get some time, because it's perform OCR and text extraction. Speed of processing depends on your hardware and number of pages in pdf.

**Comment by matt-taylor-tech** [comment]
These particular PDFs are only 2-3 pages long.  All other PDFs that have been crawled are searchable almost immediately.  I've had Ambar installed and running for a couple of days now.  I've got close to 100 PDFs that have been crawled perfectly fine.  It's just these particular ones from a certain vendor giving me issues by not showing up.

**Comment by isido993** [comment]
Hi @thesuigeneris 
Could you share one of these files with us? We'll look into the issue. Looks like the text extractor can't process them correctly.
Thnx.

**Comment by matt-taylor-tech** [comment]
I've sent a couple of the PDFs to hello@ambar.cloud, since they have private info

**Comment by isido993** [comment]
Fixed! Please update your Ambar and upload the files again. Please report the results. Thnx.

**Comment by matt-taylor-tech** [comment]
Issue resolved!  Thank you.
