### ISSUE TITLE
Feature Request:- Database Crawler

### ISSUE THREAD

**Issue by OutbackMatt** [RD17/ambar#75]
I'd love to see a database crawler for different database types. I deal with databases that store many tens of thousands of pdf or jpg or tiff as blobs, and I'd love to have a full OCR crawl performed of these documents / images.

Predominantly the database used is MS SQL Server 2008R2 or newer.

I love the concept of what you are doing here
**Just adding this to the wish list... :)

**Comment by sochix** [comment]
Hi @OutbackMatt ! Thanks for the post, but I think we will not create this type of crawler in near future as it requires a lot of work...

**Comment by OutbackMatt** [comment]
OK, so is there plans for a command line interface (CLI) or another interface so that we can programaticly send documents to be processed ad hoc.

At the moment it looks like I could create a 'drop folder', and send documents to the drop folder, and call a cron to assess all documents in this 'drop folder', and then remove the documents. That's OK, but a CLI  or API would also be useful.

**Comment by sochix** [comment]
@OutbackMatt you can use our REST API to upload files directly to Ambar. Check the documentation here https://github.com/RD17/ambar/blob/master/API_DOC.md#upload-file and the guide in our blog https://blog.ambar.cloud/ambar-use-case-integrated-parse-and-search-solution/

**Comment by sochix** [comment]
[Check our support options](https://github.com/RD17/ambar#support)
