### ISSUE TITLE
Ambar is loading ...

### ISSUE THREAD

**Issue by andychoi** [RD17/ambar#77]
I followed the [step-by-step](https://blog.ambar.cloud/ambar-installation-step-by-step-guide-2/) with same environment, ubuntu server 16.04LTS.
Docker CE version 17.06.2
However, I got "Ambar is loading..."  "Oops something went wrong" message.
I saw same error message in closed issue. Please advise.

**Comment by andychoi** [comment]
Here is docker logs for ambar_es_1
```

???@???:~/ambar$ docker logs ambar_es_1
[2017-09-23T23:49:35,795][INFO ][o.e.n.Node               ] [] initializing ...
[2017-09-23T23:49:36,116][INFO ][o.e.e.NodeEnvironment    ] [Ie2SvaC] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [2gb], net total_space [7.7gb], spins? [possibly], types [ext4]
[2017-09-23T23:49:36,117][INFO ][o.e.e.NodeEnvironment    ] [Ie2SvaC] heap size [1007.3mb], compressed ordinary object pointers [true]
[2017-09-23T23:49:36,121][INFO ][o.e.n.Node               ] node name [Ie2SvaC] derived from node ID [Ie2SvaCZSDyrJYcI0JhTJQ]; set [node.name] to override
[2017-09-23T23:49:36,122][INFO ][o.e.n.Node               ] version[5.3.2], pid[1], build[3068195/2017-04-24T16:15:59.481Z], OS[Linux/4.4.0-96-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-09-23T23:49:44,214][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [aggs-matrix-stats]
[2017-09-23T23:49:44,214][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [ingest-common]
[2017-09-23T23:49:44,215][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [lang-expression]
[2017-09-23T23:49:44,215][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [lang-groovy]
[2017-09-23T23:49:44,215][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [lang-mustache]
[2017-09-23T23:49:44,215][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [lang-painless]
[2017-09-23T23:49:44,215][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [percolator]
[2017-09-23T23:49:44,215][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [reindex]
[2017-09-23T23:49:44,215][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [transport-netty3]
[2017-09-23T23:49:44,216][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded module [transport-netty4]
[2017-09-23T23:49:44,219][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded plugin [analysis-morphology]
[2017-09-23T23:49:44,219][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded plugin [analysis-smartcn]
[2017-09-23T23:49:44,219][INFO ][o.e.p.PluginsService     ] [Ie2SvaC] loaded plugin [analysis-stempel]
[2017-09-23T23:49:54,874][INFO ][o.e.n.Node               ] initialized
[2017-09-23T23:49:54,875][INFO ][o.e.n.Node               ] [Ie2SvaC] starting ...
[2017-09-23T23:49:55,047][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: fd:e6:7b:95:ac:75:8b:00
[2017-09-23T23:49:55,152][INFO ][o.e.t.TransportService   ] [Ie2SvaC] publish_address {172.18.0.3:9300}, bound_addresses {0.0.0.0:9300}
[2017-09-23T23:49:55,180][INFO ][o.e.b.BootstrapChecks    ] [Ie2SvaC] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-09-23T23:49:58,407][INFO ][o.e.c.s.ClusterService   ] [Ie2SvaC] new_master {Ie2SvaC}{Ie2SvaCZSDyrJYcI0JhTJQ}{jY-piBssS_ShYWRrFlP32w}{172.18.0.3}{172.18.0.3:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-09-23T23:49:58,482][INFO ][o.e.h.n.Netty4HttpServerTransport] [Ie2SvaC] publish_address {172.18.0.3:9200}, bound_addresses {0.0.0.0:9200}
[2017-09-23T23:49:58,487][INFO ][o.e.g.GatewayService     ] [Ie2SvaC] recovered [0] indices into cluster_state
[2017-09-23T23:49:58,489][INFO ][o.e.n.Node               ] [Ie2SvaC] started
[2017-09-23T23:50:00,459][INFO ][o.e.c.m.MetaDataCreateIndexService] [Ie2SvaC] [ambar_log_record_data] creating index, cause [api], templates [], shards [10]/[1], mappings [ambar_log_record]
[2017-09-23T23:50:01,053][INFO ][o.e.c.m.MetaDataCreateIndexService] [Ie2SvaC] [ambar_file_data_d033e22ae348aeb5660fc2140aec35850c4da997] creating index, cause [api], templates [], shards [8]/[1], mappings [ambar_file_hidden_mark, ambar_file_tag, ambar_file]

```

**Comment by isido993** [comment]
@andychoi please post `docker logs ambar_webapi_1` logs here. Thnx.

**Comment by andychoi** [comment]
Here is docker logs on Ubuntu 16.04LTS
```
andy@ubun16:~/ambar$ docker logs ambar_webapi_1
2017/09/24 19:29:32 Waiting for host:
2017/09/24 19:29:32 Waiting for host: es:9200
2017/09/24 19:29:32 Connected to unix:///var/run/docker.sock
2017/09/24 19:29:55 Received 200 from http://es:9200
Crawler schedule service initialized
Pipeline initialized
Started on :::8080

```
Here is docker logs on CentOS 7. Same problem.
```
[andy@centos ambar]$ sudo docker logs ambar_webapi_1
2017/09/24 19:21:11 Waiting for host:
2017/09/24 19:21:11 Waiting for host: es:9200
2017/09/24 19:21:11 Connected to unix:///var/run/docker.sock
2017/09/24 19:21:29 Received 200 from http://es:9200
Crawler schedule service initialized
Pipeline initialized
Started on :::8080

```

**Comment by isido993** [comment]
Back end seems to be ok. Looks like a net issue. Please post your browser's console when receiving 'Oops something went wrong' message.

**Comment by andychoi** [comment]
![error](https://user-images.githubusercontent.com/3507699/30786056-a21689e4-a135-11e7-9a02-39090eae5269.PNG)

**Comment by andychoi** [comment]
![error](https://user-images.githubusercontent.com/3507699/30787268-6aa406ca-a14a-11e7-9dfb-eff1dfd8954a.PNG)

**Comment by andychoi** [comment]
The error is happening in NAT networking in Virtualbox. If the network is bridged, no error.
Do you use any special port to access from/to external server? I did [port forwarding VM 80 to Host 8080 ](https://www.virtualbox.org/manual/ch06.html)in NAT to test your product. Please advise it.

**Comment by isido993** [comment]
@andychoi by default Ambar uses only 80 port, so you should forward VM's 80 port to host's 80 port.

**Comment by sochix** [comment]
@andychoi did it helps?

**Comment by imperian** [comment]
I'm having the same issue.  The es and webapi logs look the same as above.  My console shows

`VM111:1 GET http://10.0.0.1:8081/api/ 502 (Bad Gateway)
(anonymous) @ VM111:1
(anonymous) @ app.e102917ba60db91d4fa5.js:5
t @ app.e102917ba60db91d4fa5.js:5
x @ app.e102917ba60db91d4fa5.js:5
(anonymous) @ app.e102917ba60db91d4fa5.js:5
app.e102917ba60db91d4fa5.js:5 Failed to start. Error: SyntaxError: Unexpected token < in JSON at position 0
(anonymous) @ app.e102917ba60db91d4fa5.js:5
Promise rejected (async)
(anonymous) @ app.e102917ba60db91d4fa5.js:5
(anonymous) @ app.e102917ba60db91d4fa5.js:52
(anonymous) @ vendor.728b3b1c29700b90277d.js:5
value @ app.e102917ba60db91d4fa5.js:28
e.notifyAll @ app.e102917ba60db91d4fa5.js:27
close @ app.e102917ba60db91d4fa5.js:51
closeAll @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:5
C @ app.e102917ba60db91d4fa5.js:5
closeAll @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
batchedUpdates @ app.e102917ba60db91d4fa5.js:28
l @ app.e102917ba60db91d4fa5.js:5
r @ app.e102917ba60db91d4fa5.js:8
enqueueSetState @ app.e102917ba60db91d4fa5.js:8
r.setState @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ vendor.728b3b1c29700b90277d.js:5
(anonymous) @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ vendor.728b3b1c29700b90277d.js:2
r @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ app.e102917ba60db91d4fa5.js:29
window.webpackJsonp @ vendor.728b3b1c29700b90277d.js:1
(anonymous) @ 2.searchPage.37654496fa9353ee17be.js:1
app.e102917ba60db91d4fa5.js:5 SyntaxError: Unexpected token < in JSON at position 0
    at app.e102917ba60db91d4fa5.js:5
    at <anonymous>
o @ app.e102917ba60db91d4fa5.js:5
(anonymous) @ app.e102917ba60db91d4fa5.js:5
Promise rejected (async)
(anonymous) @ app.e102917ba60db91d4fa5.js:5
(anonymous) @ app.e102917ba60db91d4fa5.js:52
(anonymous) @ vendor.728b3b1c29700b90277d.js:5
value @ app.e102917ba60db91d4fa5.js:28
e.notifyAll @ app.e102917ba60db91d4fa5.js:27
close @ app.e102917ba60db91d4fa5.js:51
closeAll @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:5
C @ app.e102917ba60db91d4fa5.js:5
closeAll @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
batchedUpdates @ app.e102917ba60db91d4fa5.js:28
l @ app.e102917ba60db91d4fa5.js:5
r @ app.e102917ba60db91d4fa5.js:8
enqueueSetState @ app.e102917ba60db91d4fa5.js:8
r.setState @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ vendor.728b3b1c29700b90277d.js:5
(anonymous) @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ vendor.728b3b1c29700b90277d.js:2
r @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ app.e102917ba60db91d4fa5.js:29
window.webpackJsonp @ vendor.728b3b1c29700b90277d.js:1
(anonymous) @ 2.searchPage.37654496fa9353ee17be.js:1
VM111:1 GET http://10.0.0.1:8081/api/users/check 502 (Bad Gateway)
(anonymous) @ VM111:1
(anonymous) @ app.e102917ba60db91d4fa5.js:6
t @ app.e102917ba60db91d4fa5.js:5
p @ app.e102917ba60db91d4fa5.js:6
(anonymous) @ app.e102917ba60db91d4fa5.js:6
(anonymous) @ app.e102917ba60db91d4fa5.js:52
(anonymous) @ vendor.728b3b1c29700b90277d.js:5
value @ app.e102917ba60db91d4fa5.js:28
e.notifyAll @ app.e102917ba60db91d4fa5.js:27
close @ app.e102917ba60db91d4fa5.js:51
closeAll @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:5
C @ app.e102917ba60db91d4fa5.js:5
closeAll @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
batchedUpdates @ app.e102917ba60db91d4fa5.js:28
l @ app.e102917ba60db91d4fa5.js:5
r @ app.e102917ba60db91d4fa5.js:8
enqueueSetState @ app.e102917ba60db91d4fa5.js:8
r.setState @ vendor.728b3b1c29700b90277d.js:2
a.handleChange @ vendor.728b3b1c29700b90277d.js:4
f @ vendor.728b3b1c29700b90277d.js:3
(anonymous) @ vendor.728b3b1c29700b90277d.js:5
(anonymous) @ app.e102917ba60db91d4fa5.js:52
dispatch @ vendor.728b3b1c29700b90277d.js:5
(anonymous) @ app.e102917ba60db91d4fa5.js:5
Promise rejected (async)
(anonymous) @ app.e102917ba60db91d4fa5.js:5
(anonymous) @ app.e102917ba60db91d4fa5.js:52
(anonymous) @ vendor.728b3b1c29700b90277d.js:5
value @ app.e102917ba60db91d4fa5.js:28
e.notifyAll @ app.e102917ba60db91d4fa5.js:27
close @ app.e102917ba60db91d4fa5.js:51
closeAll @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:5
C @ app.e102917ba60db91d4fa5.js:5
closeAll @ app.e102917ba60db91d4fa5.js:7
perform @ app.e102917ba60db91d4fa5.js:7
batchedUpdates @ app.e102917ba60db91d4fa5.js:28
l @ app.e102917ba60db91d4fa5.js:5
r @ app.e102917ba60db91d4fa5.js:8
enqueueSetState @ app.e102917ba60db91d4fa5.js:8
r.setState @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ vendor.728b3b1c29700b90277d.js:5
(anonymous) @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ vendor.728b3b1c29700b90277d.js:2
r @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ vendor.728b3b1c29700b90277d.js:2
(anonymous) @ app.e102917ba60db91d4fa5.js:29
window.webpackJsonp @ vendor.728b3b1c29700b90277d.js:1
(anonymous) @ 2.searchPage.37654496fa9353ee17be.js:1
app.e102917ba60db91d4fa5.js:6 Failed to auth. Error: [object Response]`

What's strange is that I had it working on this machine before.  I must have messed something up in there.

Also worth noting that if I direct the web browser directly to these locations (e.g. http://10.0.0.1:8081/api/) it works just fine and gives json output as expected.

**Comment by imperian** [comment]
Playing with this more, I'm pretty sure this has something to do with how the local network is configured (at least for me).  Ambar won't work from the local network, but if I connect to the server with a VPN and then go to the website things seem to work.  

Question: is ambar trying to connect to the proxy server through an ajax call from the browser or is it trying to connect from a docker container?  I'd guess it was an ajax call, but if not that might explain why I can connect to the /api/ directly from the browser without problem.

**Comment by BrendonUnland** [comment]
I'm having the same issue.  It worked for a while when I followed another post I changed sysctl vm.max_map_count = 262144.  However, after running a crawler for 1.5 days, I got the same response when using a browser.  Now, even after changing the setting, I get the 'Oops...Something went wrong message.'  

I attached console from browser.

![browser](https://user-images.githubusercontent.com/4040049/31110568-c78723e0-a7bc-11e7-8d7e-e070676fa089.jpg)

**Comment by hronus** [comment]
Ubuntu 16.04,  docker-engine-1.13.1-0~ubuntu-xenial, latest docker-compose.

I'm having the same issue.
```
# docker logs ambar_proxy_1   
Starting NGINX...
![ambar_502](https://user-images.githubusercontent.com/125862/32709016-2de5496e-c860-11e7-9cd7-a231cd654718.jpg)

192.168.1.47 - - [13/Nov/2017:02:27:18 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"
192.168.1.47 - - [13/Nov/2017:02:27:18 +0000] "GET /app.dd739c95d840cc540eb675b5e77f76a3.css HTTP/1.1" 304 0 "http://192.168.1.152/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"
192.168.1.47 - - [13/Nov/2017:02:27:18 +0000] "GET /vendor.13ed6fd232bee2f63b90.js HTTP/1.1" 304 0 "http://192.168.1.152/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"
192.168.1.47 - - [13/Nov/2017:02:27:18 +0000] "GET /app.7afd1ea67445fbd08460.js HTTP/1.1" 304 0 "http://192.168.1.152/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"
192.168.1.47 - - [13/Nov/2017:02:27:19 +0000] "GET /2.searchPage.0b0055b5e0d1c338bee4.js HTTP/1.1" 304 0 "http://192.168.1.152/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"
192.168.1.47 - - [13/Nov/2017:02:27:19 +0000] "GET /apiUrl.txt HTTP/1.1" 200 24 "http://192.168.1.152/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"
192.168.1.47 - - [13/Nov/2017:02:27:19 +0000] "GET /crawlerJsonTemplate.json HTTP/1.1" 304 0 "http://192.168.1.152/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"
2017/11/13 02:27:19 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.47, server: ambar-fe, request: "GET /api/ HTTP/1.1", upstream: "http://172.18.0.3:8080/api/", host: "192.168.1.152", referrer: "http://192.168.1.152/"
192.168.1.47 - - [13/Nov/2017:02:27:19 +0000] "GET /api/ HTTP/1.1" 502 575 "http://192.168.1.152/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"
2017/11/13 02:27:19 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.47, server: ambar-fe, request: "GET /api/users/check HTTP/1.1", upstream: "http://172.18.0.3:8080/api/users/check", host: "192.168.1.152", referrer: "http://192.168.1.152/"
192.168.1.47 - - [13/Nov/2017:02:27:19 +0000] "GET /api/users/check HTTP/1.1" 502 575 "http://192.168.1.152/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"
```
I think port 8080 do not passthrough out.

```
docker ps | grep 8080
3473e4ff34d4        ambar/ambar-webapi:latest     "/bin/sh -c 'docke..."   About an hour ago   Up 2 minutes        8080/tcp 
```
But next lines do not contain port 8080.
```
# ps aux | grep docker-proxy
root      4215  0.0  0.0  50856  2896 ?        Sl   09:25   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 15672 -container-ip 172.18.0.2 -container-port 15672
root      4251  0.0  0.1 116392  4948 ?        Sl   09:25   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5672 -container-ip 172.18.0.2 -container-port 5672
root      4572  0.0  0.0  50856  2924 ?        Sl   09:25   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9200 -container-ip 172.18.0.4 -container-port 9200
root      4626  0.0  0.0  50856  2924 ?        Sl   09:25   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 27017 -container-ip 172.18.0.5 -container-port 27017
root      4746  0.0  0.0  34464  2928 ?        Sl   09:25   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 6379 -container-ip 172.18.0.6 -container-port 6379
root      5858  0.0  0.0  34464  2920 ?        Sl   09:26   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.18.0.7 -container-port 80
root     27061  0.0  0.0  14164   940 pts/1    S+   10:49   0:00 grep --color=auto docker-proxy
```

I do not understand how docker network is working, but I can provide more information.
![ambar_502](https://user-images.githubusercontent.com/125862/32709225-5a7d1a8c-c861-11e7-805c-2b7c70fcbc14.jpg)

**Comment by sochix** [comment]
@hronus we will fix this issue in the next release (this week)

**Comment by hronus** [comment]
many thanks
