### ISSUE TITLE
Fresh Install: Cannot POST /api/files/Default

### ISSUE THREAD

**Issue by dwenschhof** [RD17/ambar#78]
Hi all,
  I did a fresh install and have Ambar running at http://10.0.1.9:80. Looking through the API docs, I tried to PUT my test.txt file using (test.txt file exists in my current directory):

 curl -X POST http://10.0.1.9:80/api/files/Default/test.txt -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' -F file=@test.txt

And I get the response:
Cannot POST /api/files/Default/test.txt

So, then I checked to see what Sources exist using:
curl -X GET http://10.0.1.9:80/api/sources

and I receive an empty set:
[]

Is the reason I am getting the "Cannot POST" error due to no sources existing? If so, I can not find anywhere that documents how to create a new source or endpoint? How is this done? 

Thanks in advance.

**Comment by sochix** [comment]
Hello @dwenschhof ! Did you have authentication enabled on you Ambar instance?

**Comment by dwenschhof** [comment]
Hi @sochix , thanks for your response! I currently have "auth": "none" in my config.json. Does this need to have a different value for me to do a POST?

Thanks again.

**Comment by proteusos** [comment]
it's the same problem i have.

curl -X POST \ http://MYIP/api/files/Testsource/test.pdf \ -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \ -F file=@test.pdf

curl: (6) Could not resolve host: \
curl: (26) couldn't open file "test.pdf"
curl: (6) Could not resolve host: \
curl: (6) Could not resolve host: multipart
curl: (6) Could not resolve host: boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW'
curl: (6) Could not resolve host: \

by the way...is it possible to select or name a tag by uploading a file with the gui-uploader?

thanks for help

**Comment by sochix** [comment]
Hi! It's error in our documentation.

Use `api/files/uiupload/test.pdf`

Here is sample python code

```
    filename = 'test.txt'
    files = {'file': (filename, 'TEST FILE CONTENT', 'application/vnd.ms-excel', {'content-type': 'multipart/form-data'})}
    url = 'https://app.ambar.cloud/api/files/uiupload/{0}'.format(filename)
    headers = {'ambar-email': 'YOUR_EMAIL', 'ambar-email-token': 'YOUR_TOKEN'}
    
    r = requests.post(url, files = files, headers = headers)
    print(r.status_code)
```

**Comment by proteusos** [comment]
thanks...the code is working, but where can i paste the path for the file. Or do i need to read the file with python first? Where u paste 'TEST FILE CONTENT' i can only save a string. The curl command in your doc is working now...thanks for that.

**Question:
Can i create a tag or something else, when i upload files?**

**Comment by sochix** [comment]
@proteusos as for now not

**Comment by proteusos** [comment]
@sochix thanks for your response

it's working now. Your blog describes, that i can hand over a "**:sourceId**" to the POST request. this could be Dropbox or in the example "books". So that i have a better structure, if i upload files via the rest api. So the standard tag/source is "**:uiupload**". That would be great, if you can implement this, or is it still possible?

**https://blog.ambar.cloud/ambar-use-case-integrated-parse-and-search-solution/**
