### ISSUE TITLE
Disable Signup button after one user is created

### ISSUE THREAD

**Issue by juanfcocontreras** [RD17/ambar#79]
Once I created the admin user, I think Signup button shouldn't be shown in order to prevent new users to register as admins. Is this expected behavior?

**Comment by sochix** [comment]
Hi @juanfcocontreras ! It's not a problem as in CE version only single user are allowed. In EE version this behaviour can be controlled by admin.

**Comment by juanfcocontreras** [comment]
Hi @sochix! I know that only one use is allowed in CE edition and a message is shown when the user tries to register.

But my suggestion was to remove the button, because I think the UI is not intuitive. A button without action may be confusing.

Thanks!

**Comment by sochix** [comment]
@juanfcocontreras you're right! We'll add it to roadmap

**Comment by sochix** [comment]
Hello @juanfcocontreras, we decided to leave this button as is, because it's helps users to understand difference between CE & EE
