### ISSUE TITLE
IMAP Crawler and Subfolders in Inbox

### ISSUE THREAD

**Issue by maydo** [RD17/ambar#80]
imap crawler does not crawl subfolders in Inbox.
Crawler is connected per Imap to Exchange Mailbox

**Comment by sochix** [comment]
Hello @maydo !

We'll try to investigate your issue. It's complicated as we didn't have an Exchange Mailbox. If you can create some test Exchange Mailbox for us it would be wonderful!

**Comment by maydo** [comment]
Hi,
i would like, but our exchange has no connectivity on wan side, just on lan.

i think it has something todo with (auto) "subscribing" to subfolders.
when another client is connected f.e. thunderbird per imap it just show the Inbox, subfolders needs to manually checked "subscribed"
