### ISSUE TITLE
How do I log in? What is the default username and password?

### ISSUE THREAD

**Issue by partoneoftwo** [RD17/ambar#82]
Hi

I just installed Ambar, successfully.
But one question I cannot figure out is:
How do I log in? What is the default username and password?

The email/smtp sending of emails does not work, so I cannot register, to enter the system.

Surely there is a default username and password right?

**Comment by sochix** [comment]
Hello @thomasfrivold !

we have no default login and pass - it would be non-secure. 
If you have problems with emails, try to disable authentication as for now. To do it chnage `auth` to `none` in your _config.json_ and restart Ambar.
