### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by ovv** [RD17/ambar#83]
Hello,

I set up ambar behind an haproxy to handle ssl termination. I tried to do it by using the `local` and `external` key for `api` and `fe` in the `config.json` but I couldn't get it to work that way.

Looking at the template it seems the `local` key is not used anywhere.

In the end I got it working by editing the `docker-compose.yml` file and setting the public hostname in 
the `fe` and `api` environment and using my lan configuration for the external key in `config.json`.

Am I missing something ?

Regards

**Comment by gewuerzgurke84** [comment]
+1 for a fix... Thank ovv, found the same workaround. Adjust docker-compose.yml and set external host for webapi and fe

**Comment by Ces-Ces** [comment]
Hello, I'm having issues to make my ngnix proxy work with ssl/tls. Would you mind which part of the docker-compose.yml did you change exactly?
Thanks in advance
