### ISSUE TITLE
Question: Internal Document Preview

### ISSUE THREAD

**Issue by fictionalname** [RD17/ambar#84]
Hello,

I'm really impressed with your software, but I have a question about the Document Preview.

I see that you are using Google Docs to show the contents of the documents.  The reason I want to self host my document management system is so I don't send my personal files to companies like Google.  I would prefer the preview to be handled by the Ambar server.  It seems that you have a preview on the search page, but this seems to be of low quality and is only the first page. 

Are you planning on writing your own internal preview system for documents (PDF files in particular) so the system doesn't have to go outwith the local server to show this?

Thanks for your hard work!

**Comment by sochix** [comment]
Hello @fictionalname , not as for now.

**Comment by sochix** [comment]
@fictionalname in release 1.2.0 we removed google docs preview and added internal text preview , check it out
