### ISSUE TITLE
Visualisation

### ISSUE THREAD

**Issue by neergttocsdivad** [RD17/ambar#88]
Your 'why-we-created-dtsearch-replacement/' (https://blog.ambar.cloud/why-we-created-dtsearch-replacement/) has a screenshot which includes a background image of graphs.
Do you have any information on the data visualisation aspect of ambar ?

https://mail.google.com/mail/u/0/?
![image](https://user-images.githubusercontent.com/32855774/32163014-c68abd34-bd52-11e7-9033-04de3e592be1.png)

**Comment by sochix** [comment]
Hello @neergttocsdivad , it's a statisitc tab
