### ISSUE TITLE
Installation appeared to go well, then "Oope... Something went wrong Please reload the page"

### ISSUE THREAD

**Issue by neergttocsdivad** [RD17/ambar#89]
'sudo ./ambar.py start' went well
ending with "Ambar is on http://:80"
opened browser with "http://localhost:80"
"Ambar is loading" page opened
but with error message
suggestions ?

**Comment by sochix** [comment]
Check `config.json`. You use wrong url `"Ambar is on http://:80"`

**Comment by neergttocsdivad** [comment]
I used http://:80. Didn't work
I read #43 and uninstalled then reinstalled ./ambar.py. Didn't work.
I read #45 and so cleared browser history. Didn't work
I tried different ports. Didn't work.


It's late for me to mention bit I'm using ubuntu 17.10. Is this likely to
be a/the problem ?

**Comment by sochix** [comment]
Please, post your `config.json` here

**Comment by coughlanio** [comment]
Please update your `config.json`, and set `api.external.host` to `localhost` if running locally.

**Comment by noviceiii** [comment]
The IP Adress/ Name is wrong. As mentioned above config.json needs to be edited.
The part to be corrected is
"host": "YOUR-IP-HERE",

If you don't know what to set in "YOUR-IP-HERE" do the following in your console/ terminal
- on Windows 
`ipconfig /all`

- on Linux/Mac 
`ifconfig`

and send us what it displays.
