### ISSUE TITLE
Feature Request: Admin-view of individual documents

### ISSUE THREAD

**Issue by oddomatik** [RD17/ambar#9]
I would like to see an organized and browsable view of documents available in the frontend view. Perhaps some extended statistics (time spent processing?) on an individual document, and a view of the document itself and the extracted text (without having to search for a document).

**Comment by sochix** [comment]
> I would like to see an organized and browsable view of documents available in the frontend view.

I think Ambar isn't a file explorer, it's more about search? Describe a possible scenario of this feature?

> Perhaps some extended statistics (time spent processing?)

It can be done, we'll add it to our internal roadmap

> view of the document itself and the extracted text

You can download the original file, we'll add an ability to download the extracted text in next release

**Comment by sochix** [comment]
> view of the document itself and the extracted text

Added in [Release v0.9.2](https://github.com/RD17/ambar/blob/master/CHANGELOG.md#092-2017-04-27)
