### ISSUE TITLE
ERROR: readlink /var/lib/docker/overlay2: invalid argument

### ISSUE THREAD

**Issue by neergttocsdivad** [RD17/ambar#91]
New installation appeared to go well, then error message:
I would greatfully appreciate any ideas how to resolve

ERROR: readlink /var/lib/docker/overlay2: invalid argument
Traceback (most recent call last):
  File "./ambar.py", line 300, in <module>
    start(configuration)
  File "./ambar.py", line 241, in start
    runShellCommandStrict('docker-compose -f {0}/docker-compose.yml -p ambar up -d'.format(PATH))
  File "./ambar.py", line 63, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker-compose -f /home/d/docker-compose.yml -p ambar up -d' returned non-zero exit status 1

**Comment by neergttocsdivad** [comment]
reinstalled on laptop running ubuntu 16.04 arm64 desktop and also ubuntu 16.04 arm64 server with same results, so consistently incompetent. please help.

**Comment by neergttocsdivad** [comment]
When I wrote my previous comment, I had not tried access localhost:80
I have no tried localhost:80 and been presented with 'Apache2 Ubuntu Default Page'.
Still no sign of an 'ambar' page

**Comment by sochix** [comment]
please, run `docker vesion` and `docker-compose version` . Paste the results here

**Comment by uladzimir-shelhunou** [comment]
The same issue with docker swarm, some services do not start with this error:

Used images:

mesosphere/mesos-master:1.4.0
mesosphere/mesos-slave:1.4.0

**Comment by sochix** [comment]
@vvsh I'm curious why you use these images?

**Comment by sochix** [comment]
No answer from Issue Opener
