### ISSUE TITLE
Updating to 1.2.0 without prior reset

### ISSUE THREAD

**Issue by tim-kiefer** [RD17/ambar#92]
Hi,
I would like to update from 1.0.0 to 1.2.0. The changelog tells me to run `sudo ./ambar.py reset`. This will remove the data directory and thereby remove (correct me, if I am wrong):

- all indexed documents
- all registered users (just one, but still)
- all configured crawlers

I am wondering whether there is a way to keep any of the above while still updating to the most recent version? Or is 1.2.0 just a breaking change in all dimensions?

Thanks!

**Comment by sochix** [comment]
Hello, @tim-kiefer ! Unfortunately you need to reset ambar to update to 1.2.0 because we changed ES indexes. I suggest you to wait till the next release (this week) as it requires reset too.
