### ISSUE TITLE
Is Spanish supported in OCR?

### ISSUE THREAD

**Issue by juanfcocontreras** [RD17/ambar#93]
In the [Content Extraction section of the Readme document](https://github.com/RD17/ambar/blob/master/README.md#content-extraction) and in the [FAQS](https://github.com/RD17/ambar/blob/master/README.md#which-languages-are-supported-for-ocr) says:

> Supported languages: Eng, Rus, Ita, Deu, Fra,**Spa**, Pl, Nld. If you miss your language, please create a new issue and we'll add it ASAP.

While in [the same document](https://github.com/RD17/ambar/blob/master/README.md#search)  says:

> Supported language analyzers: English `ambar_en`, Russian `ambar_ru`, German `ambar_de`, Italian `ambar_it`, Polish `ambar_pl`, Chinese `ambar_cn`, CJK `ambar_cjk`

Can I use Spanish language analyzer? If so, which is their code: `ambar_es`?

**Comment by sochix** [comment]
Hi @juanfcocontreras ! 
OCR supports SPANISH, but lang analyzer isn't. 
We'll add ES lang analyzer in the next release.

**Comment by juanfcocontreras** [comment]
Could you explain the difference?

Thanks in advance!

**Comment by sochix** [comment]
OCR is used for optical character recognition from image
Lang analyzer is used inside ElasticSearch for words tokenization
