### ISSUE TITLE
Pulling latest docker images FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by thebetterjort** [RD17/ambar#94]
Status: Image is up to date for ambar/ambar-proxy:latest

Traceback (most recent call last):
  File "./ambar.py", line 283, in <module>
    install(configuration)
  File "./ambar.py", line 203, in install
    setOsConstants()
  File "./ambar.py", line 113, in setOsConstants
    with open('/etc/rc.local', 'r') as rcLocalConfigFile:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/rc.local'

**Comment by sochix** [comment]
Hi @thebetterjort ! What command leads to this behaviour?

**Comment by thebetterjort** [comment]
sudo ./ambar.py install

**Comment by sochix** [comment]
@thebetterjort what OS you're running?

**Comment by thebetterjort** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by sochix** [comment]
Check that you have /etc/rc.local if not, just remove this lines from ambar.py. 

P.s. We recommend to use 17.04
