### ISSUE TITLE
Unable to install Ambar

### ISSUE THREAD

**Issue by shiva-kv** [RD17/ambar#95]
When I execute sudo ./ambar.py install
It throws the below error. I have all the prerequisites installed. I don't have a env directory under bin folder. I am running Cent OS 7

/usr/bin/env: python3: No such file or directory

**Comment by sochix** [comment]
install python3 or better use Ubuntu 17.04 as OS for Ambar

**Comment by shiva-kv** [comment]
Thanks, It worked with Ubuntu
