### ISSUE TITLE
[Request] Running without the ambar_internal_network

### ISSUE THREAD

**Issue by Mirabis** [RD17/ambar#96]
Hi,

I run all my containers through Rancher and tried to manually set-up Ambar on there. I managed to get most working, but got stuck on the containers trying to access the ambar_internal_network which is not created on Rancher.

Any way to circumvent the network?:
''''
11/26/2017 1:09:44 AMFailed to initialize crawler scheduler service. Error: (HTTP code 404) no such container - network ambar_internal_network not found
11/26/2017 1:09:44 AMCatastrophic failure! Error: (HTTP code 404) no such container - network ambar_internal_network not found
''''

**Comment by sochix** [comment]
Sorry @Mirabis we didn't support Rancher, in the next release we'll move all docker-compose logic to a special container maybe it'll help you

**Comment by Mirabis** [comment]
@sochix Okay thankyou, will wait for the next release(s) :)

**Comment by Mirabis** [comment]
@sochix Any update on this change?

**Comment by sochix** [comment]
@Mirabis now we removed ambar.py so you can tune docker-compose.yml for rancher as you want
