### ISSUE TITLE
[Request] Use semver rules when incrementing ambar versions

### ISSUE THREAD

**Issue by lazypower** [RD17/ambar#98]
From the 1.0.0 => 1.3.0 jump introduces non-backwards compatible changes. This is in reality a major version bump and should be labeled as a 2.0 change since it requires a full data reset on the instance.

I was caught off guard by this when issuing python ambar.py update and it happily upgraded my docker containers, but failed to inform me the indexes had changed which I observed in #92. 

I attempted a rollback and found no success. This broke around 1TB of indexed and "archived" content in my CE instance which damages my trust in the ambar project progression because a breaking change was introduced at a non-major version barrier.

I'm sorry to relay this as an issue but I didn't find a mailing list to broach this topic, and I'd love to regain some trust in the ambar project, as it really is great stuff. I just need to know my data is mostly safe in the hands of the project maintainers, and that dropping -all- data wont be required without a major revision upgrade so I can watch for and ensure i only pull updates prior to that happening since the management script is the recommended method to installation/operation.

**Comment by sochix** [comment]
@chuckbutler you're right, will keep that in mind and change update script. 

P.s. as for now you can check update instructions in changelog.md

**Comment by lazypower** [comment]
Thank you for the response and acknowledgement. :)
